framework = "ModelIO"
crate = "objc2-model-io"
required-crates = ["objc2", "objc2-foundation"]
macos = "10.11"
maccatalyst = "13.0"
ios = "9.0"
tvos = "9.0"
visionos = "1.0"

##
## Pointer bounds
##

class.MDLObject.methods."enumerateChildObjectsOfClass:root:usingBlock:stopPointer:".arguments.3.bounds = "single"

# MDLAnimatedValueTypes.h
class.MDLMatrix4x4Array.methods."setFloat4x4Array:count:".arguments.0.bounds.counted-by = "count"
class.MDLMatrix4x4Array.methods."setDouble4x4Array:count:".arguments.0.bounds.counted-by = "count"
class.MDLMatrix4x4Array.methods."getFloat4x4Array:maxCount:".arguments.0.bounds.counted-by = "max_count"
class.MDLMatrix4x4Array.methods."getDouble4x4Array:maxCount:".arguments.0.bounds.counted-by = "max_count"
class.MDLAnimatedValue.methods."getTimes:maxCount:".arguments.0.bounds.counted-by = "max_count"
class.MDLAnimatedScalarArray.methods."setFloatArray:count:atTime:".arguments.0.bounds.counted-by = "count"
class.MDLAnimatedScalarArray.methods."setDoubleArray:count:atTime:".arguments.0.bounds.counted-by = "count"
class.MDLAnimatedScalarArray.methods."getFloatArray:maxCount:atTime:".arguments.0.bounds.counted-by = "max_count"
class.MDLAnimatedScalarArray.methods."getDoubleArray:maxCount:atTime:".arguments.0.bounds.counted-by = "max_count"
class.MDLAnimatedScalarArray.methods."resetWithFloatArray:count:atTimes:count:".arguments.0.bounds.counted-by = "values_count"
class.MDLAnimatedScalarArray.methods."resetWithFloatArray:count:atTimes:count:".arguments.2.bounds.counted-by = "times_count"
class.MDLAnimatedScalarArray.methods."resetWithDoubleArray:count:atTimes:count:".arguments.0.bounds.counted-by = "values_count"
class.MDLAnimatedScalarArray.methods."resetWithDoubleArray:count:atTimes:count:".arguments.2.bounds.counted-by = "times_count"
class.MDLAnimatedScalarArray.methods."getFloatArray:maxCount:".arguments.0.bounds.counted-by = "max_count"
class.MDLAnimatedScalarArray.methods."getDoubleArray:maxCount:".arguments.0.bounds.counted-by = "max_count"
class.MDLAnimatedVector3Array.methods."setFloat3Array:count:atTime:".arguments.0.bounds.counted-by = "count"
class.MDLAnimatedVector3Array.methods."setDouble3Array:count:atTime:".arguments.0.bounds.counted-by = "count"
class.MDLAnimatedVector3Array.methods."getFloat3Array:maxCount:atTime:".arguments.0.bounds.counted-by = "max_count"
class.MDLAnimatedVector3Array.methods."getDouble3Array:maxCount:atTime:".arguments.0.bounds.counted-by = "max_count"
class.MDLAnimatedVector3Array.methods."resetWithFloat3Array:count:atTimes:count:".arguments.0.bounds.counted-by = "values_count"
class.MDLAnimatedVector3Array.methods."resetWithFloat3Array:count:atTimes:count:".arguments.2.bounds.counted-by = "times_count"
class.MDLAnimatedVector3Array.methods."resetWithDouble3Array:count:atTimes:count:".arguments.0.bounds.counted-by = "values_count"
class.MDLAnimatedVector3Array.methods."resetWithDouble3Array:count:atTimes:count:".arguments.2.bounds.counted-by = "times_count"
class.MDLAnimatedVector3Array.methods."getFloat3Array:maxCount:".arguments.0.bounds.counted-by = "max_count"
class.MDLAnimatedVector3Array.methods."getDouble3Array:maxCount:".arguments.0.bounds.counted-by = "max_count"
class.MDLAnimatedQuaternionArray.methods."setFloatQuaternionArray:count:atTime:".arguments.0.bounds.counted-by = "count"
class.MDLAnimatedQuaternionArray.methods."setDoubleQuaternionArray:count:atTime:".arguments.0.bounds.counted-by = "count"
class.MDLAnimatedQuaternionArray.methods."getFloatQuaternionArray:maxCount:atTime:".arguments.0.bounds.counted-by = "max_count"
class.MDLAnimatedQuaternionArray.methods."getDoubleQuaternionArray:maxCount:atTime:".arguments.0.bounds.counted-by = "max_count"
class.MDLAnimatedQuaternionArray.methods."resetWithFloatQuaternionArray:count:atTimes:count:".arguments.0.bounds.counted-by = "values_count"
class.MDLAnimatedQuaternionArray.methods."resetWithFloatQuaternionArray:count:atTimes:count:".arguments.2.bounds.counted-by = "times_count"
class.MDLAnimatedQuaternionArray.methods."resetWithDoubleQuaternionArray:count:atTimes:count:".arguments.0.bounds.counted-by = "values_count"
class.MDLAnimatedQuaternionArray.methods."resetWithDoubleQuaternionArray:count:atTimes:count:".arguments.2.bounds.counted-by = "times_count"
class.MDLAnimatedQuaternionArray.methods."getFloatQuaternionArray:maxCount:".arguments.0.bounds.counted-by = "max_count"
class.MDLAnimatedQuaternionArray.methods."getDoubleQuaternionArray:maxCount:".arguments.0.bounds.counted-by = "max_count"
class.MDLAnimatedScalar.methods."resetWithFloatArray:atTimes:count:".arguments.0.bounds.counted-by = "count"
class.MDLAnimatedScalar.methods."resetWithFloatArray:atTimes:count:".arguments.1.bounds.counted-by = "count"
class.MDLAnimatedScalar.methods."resetWithDoubleArray:atTimes:count:".arguments.0.bounds.counted-by = "count"
class.MDLAnimatedScalar.methods."resetWithDoubleArray:atTimes:count:".arguments.1.bounds.counted-by = "count"
class.MDLAnimatedScalar.methods."getFloatArray:maxCount:".arguments.0.bounds.counted-by = "max_count"
class.MDLAnimatedScalar.methods."getDoubleArray:maxCount:".arguments.0.bounds.counted-by = "max_count"
class.MDLAnimatedVector2.methods."resetWithFloat2Array:atTimes:count:".arguments.0.bounds.counted-by = "count"
class.MDLAnimatedVector2.methods."resetWithFloat2Array:atTimes:count:".arguments.1.bounds.counted-by = "count"
class.MDLAnimatedVector2.methods."resetWithDouble2Array:atTimes:count:".arguments.0.bounds.counted-by = "count"
class.MDLAnimatedVector2.methods."resetWithDouble2Array:atTimes:count:".arguments.1.bounds.counted-by = "count"
class.MDLAnimatedVector2.methods."getFloat2Array:maxCount:".arguments.0.bounds.counted-by = "max_count"
class.MDLAnimatedVector2.methods."getDouble2Array:maxCount:".arguments.0.bounds.counted-by = "max_count"
class.MDLAnimatedVector3.methods."resetWithFloat3Array:atTimes:count:".arguments.0.bounds.counted-by = "count"
class.MDLAnimatedVector3.methods."resetWithFloat3Array:atTimes:count:".arguments.1.bounds.counted-by = "count"
class.MDLAnimatedVector3.methods."resetWithDouble3Array:atTimes:count:".arguments.0.bounds.counted-by = "count"
class.MDLAnimatedVector3.methods."resetWithDouble3Array:atTimes:count:".arguments.1.bounds.counted-by = "count"
class.MDLAnimatedVector3.methods."getFloat3Array:maxCount:".arguments.0.bounds.counted-by = "max_count"
class.MDLAnimatedVector3.methods."getDouble3Array:maxCount:".arguments.0.bounds.counted-by = "max_count"
class.MDLAnimatedVector4.methods."resetWithFloat4Array:atTimes:count:".arguments.0.bounds.counted-by = "count"
class.MDLAnimatedVector4.methods."resetWithFloat4Array:atTimes:count:".arguments.1.bounds.counted-by = "count"
class.MDLAnimatedVector4.methods."resetWithDouble4Array:atTimes:count:".arguments.0.bounds.counted-by = "count"
class.MDLAnimatedVector4.methods."resetWithDouble4Array:atTimes:count:".arguments.1.bounds.counted-by = "count"
class.MDLAnimatedVector4.methods."getFloat4Array:maxCount:".arguments.0.bounds.counted-by = "max_count"
class.MDLAnimatedVector4.methods."getDouble4Array:maxCount:".arguments.0.bounds.counted-by = "max_count"
class.MDLAnimatedQuaternion.methods."resetWithFloatQuaternionArray:atTimes:count:".arguments.0.bounds.counted-by = "count"
class.MDLAnimatedQuaternion.methods."resetWithFloatQuaternionArray:atTimes:count:".arguments.1.bounds.counted-by = "count"
class.MDLAnimatedQuaternion.methods."resetWithDoubleQuaternionArray:atTimes:count:".arguments.0.bounds.counted-by = "count"
class.MDLAnimatedQuaternion.methods."resetWithDoubleQuaternionArray:atTimes:count:".arguments.1.bounds.counted-by = "count"
class.MDLAnimatedQuaternion.methods."getFloatQuaternionArray:maxCount:".arguments.0.bounds.counted-by = "max_count"
class.MDLAnimatedQuaternion.methods."getDoubleQuaternionArray:maxCount:".arguments.0.bounds.counted-by = "max_count"
class.MDLAnimatedMatrix4x4.methods."resetWithFloat4x4Array:atTimes:count:".arguments.0.bounds.counted-by = "count"
class.MDLAnimatedMatrix4x4.methods."resetWithFloat4x4Array:atTimes:count:".arguments.1.bounds.counted-by = "count"
class.MDLAnimatedMatrix4x4.methods."resetWithDouble4x4Array:atTimes:count:".arguments.0.bounds.counted-by = "count"
class.MDLAnimatedMatrix4x4.methods."resetWithDouble4x4Array:atTimes:count:".arguments.1.bounds.counted-by = "count"
class.MDLAnimatedMatrix4x4.methods."getFloat4x4Array:maxCount:".arguments.0.bounds.counted-by = "max_count"
class.MDLAnimatedMatrix4x4.methods."getDouble4x4Array:maxCount:".arguments.0.bounds.counted-by = "max_count"
