framework = "LocalAuthentication"
crate = "objc2-local-authentication"
required-crates = ["objc2", "objc2-foundation"]
macos = "10.10"
maccatalyst = "13.0"
ios = "8.0"
watchos = "9.0"
visionos = "1.0"

# Uses defines
enum.LABiometryType.use-value = true
const.LABiometryNone.use-value = false
enum.LACompanionType.use-value = true
enum.LAPolicy.use-value = true
enum.LACredentialType.use-value = true
enum.LAError.use-value = true
enum.LAAccessControlOperation.use-value = true

class.LAContext.methods.init.unsafe = false
class.LAContext.methods.new.unsafe = false
class.LAContext.methods.invalidate.unsafe = false
class.LAContext.methods.localizedFallbackTitle.unsafe = false
class.LAContext.methods."setLocalizedFallbackTitle:".unsafe = false
class.LAContext.methods.localizedCancelTitle.unsafe = false
class.LAContext.methods."setLocalizedCancelTitle:".unsafe = false
class.LAContext.methods.touchIDAuthenticationAllowableReuseDuration.unsafe = false
class.LAContext.methods."setTouchIDAuthenticationAllowableReuseDuration:".unsafe = false
class.LAContext.methods.localizedReason.unsafe = false
class.LAContext.methods."setLocalizedReason:".unsafe = false
class.LAContext.methods.interactionNotAllowed.unsafe = false
class.LAContext.methods."setInteractionNotAllowed:".unsafe = false
class.LAContext.methods.biometryType.unsafe = false
