framework = "LocalAuthentication"
crate = "objc2-local-authentication"
required-crates = ["objc2", "objc2-foundation"]
macos = "10.10"
maccatalyst = "13.0"
ios = "8.0"
watchos = "9.0"
visionos = "1.0"

# Uses defines
enum.LABiometryType.use-value = true
const.LABiometryNone.use-value = false
enum.LACompanionType.use-value = true
enum.LAPolicy.use-value = true
enum.LACredentialType.use-value = true
enum.LAError.use-value = true
enum.LAAccessControlOperation.use-value = true

class.LAContext.methods.init.unsafe = false
class.LAContext.methods.new.unsafe = false
class.LAContext.methods.invalidate.unsafe = false
class.LAContext.methods.localizedFallbackTitle.unsafe = false
class.LAContext.methods."setLocalizedFallbackTitle:".unsafe = false
class.LAContext.methods.localizedCancelTitle.unsafe = false
class.LAContext.methods."setLocalizedCancelTitle:".unsafe = false
class.LAContext.methods.touchIDAuthenticationAllowableReuseDuration.unsafe = false
class.LAContext.methods."setTouchIDAuthenticationAllowableReuseDuration:".unsafe = false
class.LAContext.methods.localizedReason.unsafe = false
class.LAContext.methods."setLocalizedReason:".unsafe = false
class.LAContext.methods.interactionNotAllowed.unsafe = false
class.LAContext.methods."setInteractionNotAllowed:".unsafe = false
class.LAContext.methods."canEvaluatePolicy:error:".unsafe = false
class.LAContext.methods."setCredential:type:".unsafe = false
class.LAContext.methods."isCredentialSet:".unsafe = false

class.LADomainStateBiometry.methods.biometryType.unsafe = false
class.LADomainStateBiometry.methods.stateHash.unsafe = false

class.LADomainStateCompanion.methods.availableCompanionTypes.unsafe = false
class.LADomainStateCompanion.methods.stateHash.unsafe = false
class.LADomainStateCompanion.methods."stateHashForCompanionType:".unsafe = false

class.LADomainState.methods.biometry.unsafe = false
class.LADomainState.methods.companion.unsafe = false
class.LADomainState.methods.stateHash.unsafe = false

class.LAEnvironment.methods.currentUser.unsafe = false
class.LAEnvironment.methods.state.unsafe = false

class.LAAuthenticationRequirement.methods.defaultRequirement.unsafe = false
class.LAAuthenticationRequirement.methods.biometryRequirement.unsafe = false
class.LAAuthenticationRequirement.methods.biometryCurrentSetRequirement.unsafe = false
class.LAAuthenticationRequirement.methods."biometryRequirementWithFallback:".unsafe = false

class.LABiometryFallbackRequirement.methods.defaultRequirement.unsafe = false
class.LABiometryFallbackRequirement.methods.devicePasscodeRequirement.unsafe = false

class.LARight.methods.tag.unsafe = false
class.LARight.methods."setTag:".unsafe = false
class.LARight.methods.init.unsafe = false
class.LARight.methods."initWithRequirement:".unsafe = false
class.LARight.methods.new.unsafe = false

class.LARightStore.methods.sharedStore.unsafe = false

class.LAPersistedRight.methods.key.unsafe = false
class.LAPersistedRight.methods.secret.unsafe = false

class.LAPrivateKey.methods.publicKey.unsafe = false
class.LAPrivateKey.methods."canSignUsingSecKeyAlgorithm:".unsafe = false
class.LAPrivateKey.methods."canDecryptUsingSecKeyAlgorithm:".unsafe = false
class.LAPrivateKey.methods."canExchangeKeysUsingSecKeyAlgorithm:".unsafe = false

class.LAPublicKey.methods."canEncryptUsingSecKeyAlgorithm:".unsafe = false
class.LAPublicKey.methods."canVerifyUsingSecKeyAlgorithm:".unsafe = false
