framework = "MapKit"
crate = "objc2-map-kit"
required-crates = ["objc2", "objc2-foundation"]
custom-lib-rs = true
macos = "10.9"
maccatalyst = "13.0"
ios = "3.0"
tvos = "9.2"
watchos = "2.0"
visionos = "1.0"

external.CNPostalAddress.module = "Contacts.CNPostalAddress"
typedef.MKDirectionsHandler.sendable = true
typedef.MKETAHandler.sendable = true
typedef.MKLocalSearchCompletionHandler.sendable = true
typedef.MKMapSnapshotCompletionHandler.sendable = true

# Needs proper support for iOS
class.MKMapItemRequest.methods."initWithMapFeatureAnnotation:".skipped = true
class.MKMapItemRequest.methods.mapFeatureAnnotation.skipped = true
class.MKMapItemRequest.methods.featureAnnotation.skipped = true

##
## Pointer bounds
##

fn.MKMapRectDivide.arguments.1.bounds = "single"
fn.MKMapRectDivide.arguments.2.bounds = "single"
class.MKMultiPoint.methods.points.return.bounds.counted-by = "self.pointCount()"
class.MKMultiPoint.methods."getCoordinates:range:".arguments.0.bounds.counted-by = "range.length"
class.MKPolyline.methods."polylineWithPoints:count:".arguments.0.bounds.counted-by = "count"
class.MKPolyline.methods."polylineWithCoordinates:count:".arguments.0.bounds.counted-by = "count"
class.MKPolygon.methods."polygonWithPoints:count:".arguments.0.bounds.counted-by = "count"
class.MKPolygon.methods."polygonWithPoints:count:interiorPolygons:".arguments.0.bounds.counted-by = "count"
class.MKPolygon.methods."polygonWithCoordinates:count:".arguments.0.bounds.counted-by = "count"
class.MKPolygon.methods."polygonWithCoordinates:count:interiorPolygons:".arguments.0.bounds.counted-by = "count"
class.MKGeodesicPolyline.methods."polylineWithPoints:count:".arguments.0.bounds.counted-by = "count"
class.MKGeodesicPolyline.methods."polylineWithCoordinates:count:".arguments.0.bounds.counted-by = "count"

##
## Safety
##

# Breaks type-safety, you must check encodings before accessing a value.
class.NSValue.unsafe = true
