framework = "BackgroundAssets"
crate = "objc2-background-assets"
required-crates = ["objc2", "objc2-foundation"]
macos = "13.0"
maccatalyst = "16.0"
ios = "16.0"
visionos = "1.0"

# unknown error result type Primitive(Int)
class.BAAssetPackManager.methods."fileDescriptorForPath:searchingInAssetPackWithIdentifier:error:".skipped = true
