framework = "NaturalLanguage"
crate = "objc2-natural-language"
required-dependencies = ["objc2-foundation"]
macos = "10.14"
maccatalyst = "13.0"
ios = "12.0"
tvos = "12.0"
watchos = "5.0"
visionos = "1.0"

# Needs `MLModel` from CoreML
class.NLModel.methods."modelWithMLModel:error:".skipped = true
