framework = "JavaScriptCore"
crate = "objc2-javascript-core"
required-crates = []
custom-lib-rs = true
macos = "10.5"
maccatalyst = "13.1"
ios = "7.0"
tvos = "9.0"
visionos = "1.0"

# Ends up re-defining OpaqueJSContext/OpaqueJSValue twice
typedef.JSGlobalContextRef.skipped = true
typedef.JSObjectRef.skipped = true

##
## Pointer bounds
##

fn.JSEvaluateScript.arguments.5.bounds = "single"
fn.JSCheckScriptSyntax.arguments.4.bounds = "single"

fn.JSValueGetTypedArrayType.arguments.2.bounds = "single"
fn.JSValueIsEqual.arguments.3.bounds = "single"
fn.JSValueIsInstanceOfConstructor.arguments.3.bounds = "single"
fn.JSValueCompare.arguments.3.bounds = "single"
fn.JSValueCompareInt64.arguments.3.bounds = "single"
fn.JSValueCompareUInt64.arguments.3.bounds = "single"
fn.JSValueCompareDouble.arguments.3.bounds = "single"
fn.JSBigIntCreateWithDouble.arguments.2.bounds = "single"
fn.JSBigIntCreateWithInt64.arguments.2.bounds = "single"
fn.JSBigIntCreateWithUInt64.arguments.2.bounds = "single"
fn.JSBigIntCreateWithString.arguments.2.bounds = "single"
fn.JSValueCreateJSONString.arguments.3.bounds = "single"
fn.JSValueToNumber.arguments.2.bounds = "single"
fn.JSValueToInt32.arguments.2.bounds = "single"
fn.JSValueToUInt32.arguments.2.bounds = "single"
fn.JSValueToInt64.arguments.2.bounds = "single"
fn.JSValueToUInt64.arguments.2.bounds = "single"
fn.JSValueToStringCopy.arguments.2.bounds = "single"
fn.JSValueToObject.arguments.2.bounds = "single"

fn.JSClassCreate.arguments.0.bounds = "single"
fn.JSObjectMakeArray.arguments.2.bounds.counted-by = "argument_count"
fn.JSObjectMakeArray.arguments.3.bounds = "single"
fn.JSObjectMakeDate.arguments.2.bounds.counted-by = "argument_count"
fn.JSObjectMakeDate.arguments.3.bounds = "single"
fn.JSObjectMakeError.arguments.2.bounds.counted-by = "argument_count"
fn.JSObjectMakeError.arguments.3.bounds = "single"
fn.JSObjectMakeRegExp.arguments.2.bounds.counted-by = "argument_count"
fn.JSObjectMakeRegExp.arguments.3.bounds = "single"
fn.JSObjectMakeDeferredPromise.arguments.1.bounds = "single"
fn.JSObjectMakeDeferredPromise.arguments.2.bounds = "single"
fn.JSObjectMakeDeferredPromise.arguments.3.bounds = "single"
fn.JSObjectMakeFunction.arguments.3.bounds.counted-by = "parameter_count"
fn.JSObjectMakeFunction.arguments.7.bounds = "single"
fn.JSObjectGetProperty.arguments.3.bounds = "single"
fn.JSObjectSetProperty.arguments.5.bounds = "single"
fn.JSObjectDeleteProperty.arguments.3.bounds = "single"
fn.JSObjectHasPropertyForKey.arguments.3.bounds = "single"
fn.JSObjectGetPropertyForKey.arguments.3.bounds = "single"
fn.JSObjectSetPropertyForKey.arguments.5.bounds = "single"
fn.JSObjectDeletePropertyForKey.arguments.3.bounds = "single"
fn.JSObjectGetPropertyAtIndex.arguments.3.bounds = "single"
fn.JSObjectSetPropertyAtIndex.arguments.4.bounds = "single"
fn.JSObjectCallAsFunction.arguments.4.bounds.counted-by = "argument_count"
fn.JSObjectCallAsFunction.arguments.5.bounds = "single"
fn.JSObjectCallAsConstructor.arguments.3.bounds.counted-by = "argument_count"
fn.JSObjectCallAsConstructor.arguments.4.bounds = "single"

fn.JSObjectMakeTypedArray.arguments.3.bounds = "single"
fn.JSObjectMakeTypedArrayWithBytesNoCopy.arguments.2.bounds.sized-by = "byte_length"
fn.JSObjectMakeTypedArrayWithBytesNoCopy.arguments.6.bounds = "single"
fn.JSObjectMakeTypedArrayWithArrayBuffer.arguments.3.bounds = "single"
fn.JSObjectMakeTypedArrayWithArrayBufferAndOffset.arguments.5.bounds = "single"
fn.JSObjectGetTypedArrayBytesPtr.arguments.2.bounds = "single"
fn.JSObjectGetTypedArrayLength.arguments.2.bounds = "single"
fn.JSObjectGetTypedArrayByteLength.arguments.2.bounds = "single"
fn.JSObjectGetTypedArrayByteOffset.arguments.2.bounds = "single"
fn.JSObjectGetTypedArrayBuffer.arguments.2.bounds = "single"
fn.JSObjectMakeArrayBufferWithBytesNoCopy.arguments.1.bounds.sized-by = "byte_length"
fn.JSObjectMakeArrayBufferWithBytesNoCopy.arguments.5.bounds = "single"
fn.JSObjectGetArrayBufferBytesPtr.arguments.2.bounds = "single"
fn.JSObjectGetArrayBufferByteLength.arguments.2.bounds = "single"

fn.JSStringCreateWithCharacters.arguments.0.bounds.counted-by = "num_chars"
fn.JSStringCreateWithUTF8CString.arguments.0.bounds = "null-terminated"
fn.JSStringGetCharactersPtr.return.bounds.counted-by = "JSStringGetLength(string)"
fn.JSStringGetUTF8CString.arguments.1.bounds.counted-by = "buffer_size"
fn.JSStringIsEqualToUTF8CString.arguments.1.bounds = "null-terminated"
