[package]
name = "test_ns_string"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "lib.rs"

[dependencies]
objc2-foundation = { path = "../../../../framework-crates/objc2-foundation" }

[features]
default = ["all"]

# Runtime
gnustep-1-7 = ["objc2-foundation/gnustep-1-7"]
gnustep-1-8 = ["gnustep-1-7", "objc2-foundation/gnustep-1-8"]
gnustep-1-9 = ["gnustep-1-8", "objc2-foundation/gnustep-1-9"]
gnustep-2-0 = ["gnustep-1-9", "objc2-foundation/gnustep-2-0"]
gnustep-2-1 = ["gnustep-2-0", "objc2-foundation/gnustep-2-1"]

all = ["objc2-foundation/block2", "objc2-foundation/NSString"]

# Hack
assembly-features = ["all", "objc2-foundation/unstable-static-nsstring"]

[package.metadata.release]
release = false
