framework = "CoreLocation"
crate = "objc2-core-location"
required-crates = ["objc2", "objc2-foundation"]
custom-lib-rs = true
# macos = "10.6"
macos = "10.11"      # Temporarily raised since `CoreLocation` imports `Contacts`
maccatalyst = "13.0"
ios = "2.0"
tvos = "9.0"
watchos = "2.0"
visionos = "1.0"

external.CNPostalAddress.module = "Contacts.CNPostalAddress"

# error: translator assertion failure: (left `"CLLocation"`) (right `"const CLLocation"`)
class.CLLocation.methods."getDistanceFrom:".skipped = true
class.CLLocation.methods."distanceFromLocation:".skipped = true
