[package]
name = "examples-audio"
version = "0.0.0"
edition = "2021"
license = "Zlib OR Apache-2.0 OR MIT"
publish = false

[[example]]
name = "speech_synthesis"
path = "speech_synthesis.rs"

[features]
unstable-darwin-objc = [
    "objc2/unstable-darwin-objc",
    "objc2-foundation/unstable-darwin-objc",
]

[dependencies]
objc2 = "0.6.2"
objc2-foundation = { version = "0.3.2", default-features = false, features = [
    "std",
    "NSString",
    "NSObject",
] }
