framework = "CoreServices"
crate = "objc2-core-services"
required-crates = ["objc2-core-foundation"]
custom-lib-rs = true
macos = "10.0"
maccatalyst = "13.0"
ios = "12.0"
tvos = "12.0"
watchos = "5.0"
visionos = "1.0"

# Deprecated, replaced with functionality in Security.
module.OSServices.module.KeychainCore.skipped = true
# Deprecated, replaced with functionality in IOKit.
module.OSServices.module.Power.skipped = true
# Deprecated, replaced with other LSOpen functions.
module.LaunchServices.module.LSOpenDeprecated.skipped = true
# Deprecated, replaced with other LSInfo functions.
module.LaunchServices.module.LSInfoDeprecated.skipped = true

# Affects CarbonCore.Files, and unclear why this is even created?
module.Files.skipped = true

# Needs acl_t from include/sys/acl.h
fn.FSFileSecurityCopyAccessControlList.skipped = true
fn.FSFileSecuritySetAccessControlList.skipped = true

# Ends up declaring __FSEventStream twice.
typedef.ConstFSEventStreamRef.skipped = true

# Needs va_list
fn.vAEBuildDesc.skipped = true
fn.vAEBuildParameters.skipped = true
fn.vAEBuildAppleEvent.skipped = true

# Dependent on target endianness
union.WideChar.skipped = true
typedef.WideChar.skipped = true

# Needs mach_msg_header_t
fn.AEDecodeMessage.skipped = true
fn.AEProcessMessage.skipped = true

# Kinda weird, uses UniversalProcPtr, which is defined in MacTypes.h,
# which points to RoutineDescriptor, which is defined in CoreServices.
typedef.ComponentFunctionUPP.skipped = true
fn.NewComponentFunctionUPP.skipped = true
fn.DisposeComponentFunctionUPP.skipped = true
fn.CallComponentFunction.skipped = true
fn.CallComponentFunctionWithStorage.skipped = true

# Defaults to c_ulong, which is wrong on 32-bit targets.
const.kFSEventStreamEventIdSinceNow.skipped = true

# Tries to OR u32s and i32s.
const.kIconServicesCatalogInfoMask.use-value = true

# Literals are out of the i32 range.
const.kFSCatInfoReserved.use-value = true
const.kFSIterateReserved.use-value = true
const.kioACAccessOwnerMask.use-value = true
const.kHelpFolderIcon.use-value = true
const.kInternetPlugInFolderIcon.use-value = true
const.kLocalesFolderIcon.use-value = true
const.kPrinterDriverFolderIcon.use-value = true
const.kScriptingAdditionsFolderIcon.use-value = true
const.kSharedLibrariesFolderIcon.use-value = true
const.kTextEncodingsFolderIcon.use-value = true
const.kAEDebugXMLDebugAll.use-value = true

# Deprecated and only defined on 32-bit architectures
const.typeSMInt.skipped = true
const.typeShortInteger.skipped = true
const.typeInteger.skipped = true
const.typeLongInteger.skipped = true
const.typeMagnitude.skipped = true
const.typeComp.skipped = true
const.typeSMFloat.skipped = true
const.typeShortFloat.skipped = true
const.typeFloat.skipped = true
const.typeLongFloat.skipped = true
const.typeExtended.skipped = true
const.typeFSS.skipped = true

# Needs long double
fn.relationl.skipped = true
fn.num2decl.skipped = true
fn.dec2numl.skipped = true
fn.x80told.skipped = true
fn.ldtox80.skipped = true
fn.SInt64ToLongDouble.skipped = true
fn.LongDoubleToSInt64.skipped = true
fn.UInt64ToLongDouble.skipped = true
fn.LongDoubleToUInt64.skipped = true

# Recursive, we must define it ourselves to get the encoding right.
struct.QElem.skipped = true

# Wrong type of value.
const.WDEFNFnd.use-value = true
const.CDEFNFnd.use-value = true

# Uses kInvalidID from MacTypes.h
const.kMPNoID.use-value = true

# Literal overflows i32, needs to be cast / converted to a negative literal.
const.kCollectionAllAttributes.use-value = true
const.gestaltAFPClientAttributeMask.use-value = true
const.gestaltUSBPrinterSharingAttrMask.use-value = true
const.gestaltUSBPrinterSharingAttrRunning.use-value = true
const.badComponentInstance.use-value = true
const.badComponentSelector.use-value = true
const.kStackParameterMask.use-value = true
const.kXLibTag1.use-value = true
const.smMaskAll.use-value = true

# Private
const._MixedModeMagic.skipped = true

# Uses `_FILESEC_REMOVE_ACL` from sys/fcntl.h
const.kFSFileSecurityRemoveACL.skipped = true

# Uses sizeof(PEFContainerHeader), which is not yet supported.
# Note: `PEFContainerHeader` has a fixed size regardless of architecture, so
# it's fine to just use the value.
const.kPEFFirstSectionHeaderOffset.use-value = true

##
## Nullability, lifetime and pointer bounds.
##

fn.MDQueryCreateSubset.arguments.1.nullability = "nonnull"

fn.CSIdentityCreateCopy.arguments.1.nullability = "nonnull"
fn.CSIdentityCreatePersistentReference.arguments.1.nullability = "nonnull"
fn.CSIdentityCreateGroupMembershipQuery.arguments.1.nullability = "nonnull"

# These seem to be arrays?
fn.SKIndexCopyInfoForDocumentIDs.arguments.3.bounds = "unsafe"
fn.SKIndexCopyDocumentRefsForDocumentIDs.arguments.3.bounds = "unsafe"
fn.SKIndexCopyDocumentURLsForDocumentIDs.arguments.3.bounds = "unsafe"
fn.SKSearchResultsGetInfoInRange.arguments.2.bounds = "unsafe"
fn.SKSearchResultsGetInfoInRange.arguments.3.bounds = "unsafe"

# Docs says: Despite the absence of the word Copy [...] you are responsible for releasing this object.
fn.LSOpenCFURLRef.arguments.1.lifetime = "out-pointer-retained"
fn.LSOpenFromURLSpec.arguments.1.lifetime = "out-pointer-retained"

# Header says: Returned values has to be released with CFRelease().
fn.LSSharedFileListItemResolve.arguments.2.lifetime = "out-pointer-retained"

# Docs say: The caller is responsible for releasing the returned CFUUID.
fn.CSDiskSpaceStartRecovery.arguments.3.lifetime = "out-pointer-retained"

# _Probably_ creates the output string.
fn.InvokeIndexToUCStringUPP.arguments.3.lifetime = "out-pointer-retained"

##
## Safety.
##

fn.SKDocumentGetTypeID.unsafe = false
