use std::collections::BTreeMap;
use std::fmt;
use std::fs;
use std::io;
use std::path::Path;

use crate::config::LibraryData;
use crate::file::File;

#[derive(Debug, PartialEq, Default)]
pub struct Library {
    pub files: BTreeMap<String, File>,
    link_name: String,
    data: LibraryData,
}

impl Library {
    pub fn new(name: &str, data: &LibraryData) -> Self {
        Self {
            files: BTreeMap::new(),
            link_name: name.to_string(),
            data: data.clone(),
        }
    }

    pub fn output(&self, path: &Path) -> io::Result<()> {
        for (name, file) in &self.files {
            // NOTE: some SDK files have '+' in the file name
            let name = name.replace('+', "_");
            let mut path = path.join(name);
            path.set_extension("rs");
            fs::write(&path, file.to_string())?;
        }

        // truncate if the file exists
        fs::write(path.join("mod.rs"), self.to_string())?;

        Ok(())
    }

    pub fn compare(&self, other: &Self) {
        super::compare_btree(&self.files, &other.files, |name, self_file, other_file| {
            let _span = debug_span!("file", name).entered();
            self_file.compare(other_file);
        });
    }
}

impl fmt::Display for Library {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        writeln!(
            f,
            "// This file has been automatically generated by `objc2`'s `header-translator`."
        )?;
        writeln!(f, "// DO NOT EDIT")?;
        writeln!(f)?;
        writeln!(f, "//! # Bindings to the `{}` framework", self.link_name)?;
        writeln!(f)?;

        // Link to the correct framework
        //
        // FIXME: We always do cfg_attr(feature = "apple", ...) to make compiling things for GNUStep easier.
        writeln!(
            f,
            "#[cfg_attr(feature = \"apple\", link(name = \"{}\", kind = \"framework\"))]",
            self.link_name
        )?;
        if let Some(gnustep_library) = &self.data.gnustep_library {
            writeln!(
                f,
                "#[cfg_attr(feature = \"gnustep-1-7\", link(name = \"{}\", kind = \"dylib\"))]",
                gnustep_library
            )?;
        }
        writeln!(f, "extern \"C\" {{}}")?;
        writeln!(f)?;

        for name in self.files.keys() {
            // NOTE: some SDK files have '+' in the file name
            let name = name.replace('+', "_");
            writeln!(f, "#[path = \"{name}.rs\"]")?;
            writeln!(f, "mod __{name};")?;
        }

        writeln!(f)?;

        for (file_name, file) in &self.files {
            // NOTE: some SDK files have '+' in the file name
            let file_name = file_name.replace('+', "_");
            for stmt in &file.stmts {
                let features = stmt.features();

                if let Some(name) = stmt.name() {
                    write!(f, "{}", features.cfg_gate_ln())?;

                    let visibility = if name.starts_with('_') {
                        "pub(crate)"
                    } else {
                        "pub"
                    };

                    write!(f, "{visibility} use self::__{file_name}::{{{name}}};")?;
                }

                let extra_declared_types = stmt.extra_declared_types();
                if !extra_declared_types.is_empty() {
                    write!(f, "{}", features.cfg_gate_ln())?;
                    write!(f, "pub use self::__{file_name}::{{")?;
                    for item in extra_declared_types {
                        writeln!(f, "    {item},")?;
                    }
                    writeln!(f, "}};")?;
                }
            }
        }

        Ok(())
    }
}
