framework = "SensitiveContentAnalysis"
crate = "objc2-sensitive-content-analysis"
required-crates = ["objc2", "objc2-foundation"]
macos = "14.0"
maccatalyst = "17.0"
ios = "17.0"

external.AVCaptureDeviceInput.module = "AVFoundation.AVCaptureInput"
