framework = "ClassKit"
crate = "objc2-class-kit"
required-dependencies = ["objc2-foundation"]
macos = "11.0"
maccatalyst = "14.0"
ios = "11.4"
visionos = "1.0"

# Needs `CGImageRef`
class.CLSContext.methods.thumbnail.skipped = true
class.CLSContext.methods."setThumbnail:".skipped = true
