framework = "CoreBluetooth"
crate = "objc2-core-bluetooth"
required-dependencies = ["objc2-foundation"]
macos = "10.10"
maccatalyst = "13.0"
ios = "5.0"
tvos = "9.0"
watchos = "4.0"
visionos = "1.0"

# Needs `dispatch_queue_t`
class.CBCentralManager.methods."initWithDelegate:queue:".skipped = true
class.CBCentralManager.methods."initWithDelegate:queue:options:".skipped = true
class.CBPeripheralManager.methods."initWithDelegate:queue:".skipped = true
class.CBPeripheralManager.methods."initWithDelegate:queue:options:".skipped = true

# Needs `CFAbsoluteTime`
protocol.CBCentralManagerDelegate.methods."centralManager:didDisconnectPeripheral:timestamp:isReconnecting:error:".skipped = true

# Needs `CFUUIDRef`
class.CBUUID.methods."UUIDWithCFUUID:".skipped = true
