framework = "CFNetwork"
crate = "objc2-cf-network"
required-crates = ["objc2-core-foundation"]
custom-lib-rs = true
macos = "10.8"
maccatalyst = "13.0"
ios = "2.0"
tvos = "9.0"
visionos = "1.0"

##
## Pointer bounds
##

fn.CFHostStartInfoResolution.arguments.2.bounds = "single"
fn.CFHostGetAddressing.arguments.1.bounds = "single"
fn.CFHostGetNames.arguments.1.bounds = "single"
fn.CFHostGetReachability.arguments.1.bounds = "single"
fn.CFHostSetClient.arguments.2.bounds = "single"

fn.CFNetServiceRegisterWithOptions.arguments.2.bounds = "single"
fn.CFNetServiceResolveWithTimeout.arguments.2.bounds = "single"
fn.CFNetServiceSetClient.arguments.2.bounds = "single"
fn.CFNetServiceMonitorCreate.arguments.3.bounds = "single"
fn.CFNetServiceMonitorStart.arguments.2.bounds = "single"
fn.CFNetServiceMonitorStop.arguments.1.bounds = "single"
fn.CFNetServiceBrowserCreate.arguments.2.bounds = "single"
fn.CFNetServiceBrowserSearchForDomains.arguments.2.bounds = "single"
fn.CFNetServiceBrowserSearchForServices.arguments.3.bounds = "single"
fn.CFNetServiceBrowserStopSearch.arguments.1.bounds = "single"
fn.CFNetServiceRegister.arguments.1.bounds = "single"
fn.CFNetServiceResolve.arguments.1.bounds = "single"

fn.CFSocketStreamSOCKSGetErrorSubdomain.arguments.0.bounds = "single"
fn.CFSocketStreamSOCKSGetError.arguments.0.bounds = "single"

fn.CFFTPCreateParsedResourceListing.arguments.1.bounds.counted-by = "buffer_length"

fn.CFHTTPMessageAppendBytes.arguments.1.bounds.counted-by = "num_bytes"
fn.CFHTTPAuthenticationIsValid.arguments.1.bounds = "single"
fn.CFHTTPMessageApplyCredentials.arguments.4.bounds = "single"
fn.CFHTTPMessageApplyCredentialDictionary.arguments.3.bounds = "single"

fn.CFNetworkExecuteProxyAutoConfigurationScript.arguments.3.bounds = "single"
fn.CFNetworkExecuteProxyAutoConfigurationURL.arguments.3.bounds = "single"

##
## Generics
##

fn.CFFTPCreateParsedResourceListing.arguments.3.generics = ["CoreFoundation.CFString.CFString", "CoreFoundation.CFType"]

fn.CFHostGetAddressing.return.generics = ["CoreFoundation.CFData.CFData"]
fn.CFHostGetNames.return.generics = ["CoreFoundation.CFString.CFString"]

fn.CFHTTPMessageApplyCredentialDictionary.arguments.2.generics = ["CoreFoundation.CFString.CFString", "CoreFoundation.CFType"]
fn.CFHTTPAuthenticationCopyDomains.return.generics = ["CoreFoundation.CFURL.CFURL"] # Probably

fn.CFHTTPMessageCopyAllHeaderFields.return.generics = ["CoreFoundation.CFString.CFString", "CoreFoundation.CFType"] # Maybe CFString value?

fn.CFNetServiceGetAddressing.return.generics = ["CoreFoundation.CFData.CFData"]
fn.CFNetServiceCreateDictionaryWithTXTData.return.generics = ["CoreFoundation.CFString.CFString", "CoreFoundation.CFData.CFData"]
# Dict values can also be CFString for convenience, but let's not support that to allow passing ^ directly to this.
fn.CFNetServiceCreateTXTDataWithDictionary.arguments.1.generics = ["CoreFoundation.CFString.CFString", "CoreFoundation.CFData.CFData"]

fn.CFNetworkCopySystemProxySettings.return.generics = ["CoreFoundation.CFString.CFString", "CoreFoundation.CFType"]
fn.CFNetworkCopyProxiesForURL.arguments.1.generics = ["CoreFoundation.CFString.CFString", "CoreFoundation.CFType"]
fn.CFNetworkCopyProxiesForURL.return.generics = ["CoreFoundation.CFDictionary.CFDictionary<CoreFoundation.CFString.CFString, CoreFoundation.CFType>"]
fn.CFNetworkCopyProxiesForAutoConfigurationScript.return.generics = ["CoreFoundation.CFDictionary.CFDictionary<CoreFoundation.CFString.CFString, CoreFoundation.CFType>"]
