framework = "LocalAuthenticationEmbeddedUI"
crate = "objc2-local-authentication-embedded-ui"
required-dependencies = ["objc2-foundation", "objc2-local-authentication"]
macos = "12.0"
maccatalyst = "16.0"
ios = "16.0"
visionos = "1.0"
