framework = "IOSurface"
crate = "objc2-io-surface"
required-crates = []
custom-lib-rs = true
macos = "10.6"
maccatalyst = "13.0"
# NOTE: IOSurface.tbd in the iOS SDK does contain some $ld$previous$
# directives, but they only work when using Swift's auto-linking, not when
# telling the linker to link the framework directly via the commandline (as
# Rust does).
ios = "11.0"
tvos = "11.0"
visionos = "1.0"

# Needs xpc_object_t
fn.IOSurfaceCreateXPCObject.skipped = true
fn.IOSurfaceLookupFromXPCObject.skipped = true

# Defined in other crates too, so needs manual definition
typedef.IOSurfaceRef.renamed = "IOSurfaceRef" # TODO: Merge IOSurface and IOSurfaceRef somehow
typedef.IOSurfaceRef.skipped = true
struct.__IOSurface.skipped = true
external.IOSurfaceRef.module = "IOSurface.IOSurfaceRef"

# Fix generics
fn.IOSurfaceCreate.arguments.0.generics = ["CoreFoundation.CFString.CFString", "CoreFoundation.CFType"]
fn.IOSurfaceSetValues.arguments.1.generics = ["CoreFoundation.CFString.CFString", "CoreFoundation.CFType"]
fn.IOSurfaceCopyAllValues.return.generics = ["CoreFoundation.CFString.CFString", "CoreFoundation.CFType"]

# Pointer bounds
fn.IOSurfaceLock.arguments.2.bounds = "single"
fn.IOSurfaceUnlock.arguments.2.bounds = "single"
fn.IOSurfaceSetPurgeable.arguments.2.bounds = "single"
class.IOSurface.methods."lockWithOptions:seed:".arguments.1.bounds = "single"
class.IOSurface.methods."unlockWithOptions:seed:".arguments.1.bounds = "single"
class.IOSurface.methods."setPurgeable:oldState:".arguments.1.bounds = "single"

##
## Safety
##

# SAFETY: IOSurface methods and functions are well-behaved.
unsafe-default-safety.documentation-is-reviewed = true

# Surface properties must be specified correctly, especially `kIOSurfaceCacheMode`.
#
# Changing surface _values_ (which are distinct from properties) is fine though.
fn.IOSurfaceCreate.unsafe = true
class.IOSurface.methods."initWithProperties:".unsafe = true

# Unsure if `task_id_token_t` means that this remaps the underlying memory
# somehow?
fn.IOSurfaceSetOwnershipIdentity.unsafe = true

# Making a surface purgeable can likely cause problems elsewhere.
fn.IOSurfaceSetPurgeable.unsafe = true
class.IOSurface.methods."setPurgeable:oldState:".unsafe = true
