[[example]]
name = "browser"
required-features = [
    "objc2-app-kit",
    "objc2-app-kit/NSResponder",
    "objc2-app-kit/NSView",
    "objc2-app-kit/NSColor",
    "objc2-app-kit/NSButton",
    "objc2-app-kit/NSButtonCell",
    "objc2-app-kit/NSMenu",
    "objc2-app-kit/NSMenuItem",
    "objc2-app-kit/NSStackView",
    "objc2-app-kit/NSText",
    "objc2-app-kit/NSTextField",
    "objc2-app-kit/NSTextView",
    "objc2-app-kit/NSWindow",
    "objc2-app-kit/NSControl",
    "objc2-app-kit/NSApplication",
    "objc2-app-kit/NSRunningApplication",
    "objc2-app-kit/NSGraphics",
    "objc2-app-kit/NSLayoutConstraint",
    "objc2-app-kit/NSUserInterfaceLayout",
    "objc2-foundation/NSString",
    "objc2-foundation/NSGeometry",
    "objc2-foundation/NSNotification",
    "objc2-foundation/NSURL",
    "objc2-foundation/NSURLRequest",
    "objc2-foundation/NSThread",
    "WKNavigation",
    "WKNavigationDelegate",
    "WKWebView",
]
