[class.NSObject.methods]
# Uses NS_REPLACES_RECEIVER
awakeAfterUsingCoder = { skipped = true }

[class.NSKeyedUnarchiverDelegate.methods]
# Uses NS_RELEASES_ARGUMENT and NS_RETURNS_RETAINED
unarchiver_didDecodeObject = { skipped = true }

[class.NSString.methods]
new = { unsafe = false }
# Assuming that (non-)nullability is properly set
stringByAppendingString = { unsafe = false }
stringByAppendingPathComponent = { unsafe = false }
# Assuming `NSStringEncoding` can be made safe
lengthOfBytesUsingEncoding = { unsafe = false }
length = { unsafe = false }
# Safe to call, but the returned pointer may not be safe to use
UTF8String = { unsafe = false }

[class.NSMutableString.methods]
new = { unsafe = false }
initWithString = { unsafe = false }
# "appendString:" = { unsafe = false, mutable = true }
# "setString:" = { unsafe = false, mutable = true }
