[package]
name = "icrate"
version = "0.0.1"
authors = ["Mads Marquart <mads@marquart.dk>"]
edition = "2021"

description = "Bindings to Apple's frameworks"
keywords = ["macos", "ios", "cocoa", "apple", "framework"]
categories = [
    "accessibility",
    "api-bindings",
    "development-tools::ffi",
    "external-ffi-bindings",
    "os::macos-apis",
]
readme = "README.md"
repository = "https://github.com/madsmtm/objc2"
documentation = "https://docs.rs/icrate/"
license = "MIT"

[dependencies]
# This does not support GNUStep or other runtimes
objc2 = { path = "../objc2", version = "=0.3.0-beta.3", default-features = false, optional = true, features = ["apple"] }
block2 = { path = "../block2", version = "=0.2.0-alpha.6", default-features = false, optional = true }

[package.metadata.docs.rs]
default-target = "x86_64-apple-darwin"
all-features = true

targets = [
    # MacOS
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    # "i686-apple-darwin",
    # iOS
    "aarch64-apple-ios",
    "x86_64-apple-ios",
    # "armv7-apple-ios",
    # "i386-apple-ios",
    # GNUStep
    "x86_64-unknown-linux-gnu",
    "i686-unknown-linux-gnu",
    # Windows
    "x86_64-pc-windows-msvc",
]

[features]
default = ["std"]

# Currently not possible to turn off, put here for forwards compatibility.
std = ["alloc", "objc2?/std"]
alloc = ["objc2?/alloc"]

# Expose features that requires Objective-C.
objective-c = ["objc2"]

# Expose features that requires creating blocks.
block = ["objc2?/block", "block2"]

# For better documentation on docs.rs
unstable-docsrs = []

# Frameworks
# Based on:
# - https://developer.apple.com/documentation/technologies
# - https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/OSX_Technology_Overview/SystemFrameworks/SystemFrameworks.html
# - https://github.com/youknowone/apple-sys

# Accelerate = []
# Accessibility = []
# Accounts = []
# AddressBook = [] # + AddressBookUI.h
# AdServices = []
# AdSupport = []
# AGL = []
# AppClip = []
# AppIntents = []
# AppTrackingTransparency = []
AppKit = ["objective-c", "Foundation", "CoreData"]
# AppleScriptKit = []
# AppleScriptObjC = []
# ApplicationServices = []
# AppTrackingTransparency = []
# ARKit = []
# AssetsLibrary = [] # iOS
# AudioToolbox = []
# AudioUnit = []
# AudioDriverKit = []
# AudioVideoBridging = []
# AuthenticationServices = []
# AutomaticAssessmentConfiguration = []
# Automator = []
# AVFAudio = []
# AVFoundation = []
# AVKit = []
# BackgroundTasks = []
# BusinessChat = []
# CalendarStore = []
# CallKit = []
# Carbon = []
# CareKit = []
# CarPlay = [] # iOS
# CFNetwork = []
# CHIP = []
# ClassKit = []
# ClockKit = []
# CloudKit = []
# Cocoa = []
# Collaboration = []
# ColorSync = []
# Combine = []
# Compression = []
# Contacts = []
# ContactsUI = []
# CoreAudio = []
# CoreAudioKit = []
# CoreAudioTypes = []
# CoreBluetooth = []
CoreData = ["objective-c", "Foundation"]
# CoreFoundation = []
# CoreGraphics = []
# CoreHaptics = []
# CoreImage = []
# CoreLocation = []
# CoreLocationUI = []
# CoreMedia = []
# CoreMediaIO = []
# CoreMIDI = []
# CoreML = []
# CoreMotion = []
# CoreNFC = []
# CoreServices = []
# CoreSpotlight = []
# CoreTelephony = []
# CoreText = []
# CoreTransferable = []
# CoreVideo = []
# CoreWLAN = []
# CreateML = []
# CreateMLComponents = []
# CryptoTokenKit = []
# DataDetection = []
# DeveloperToolsSupport = []
# DeviceActivity = []
# DeviceManagement = []
# DeviceCheck = []
# DeviceDiscoveryExtension = []
# DeviceDiscoveryUI = []
# DirectoryService = []
# DiscRecording = []
# DiscRecordingUI = []
# DiskArbitration = []
# dispatch = []
# Distributed = []
# dnssd = []
# DocC = []
# DriverKit = []
# DVDPlayback = []
# Endpoint Security = []
# EventKit = []
# EventKitUI = []
# ExceptionHandling = []
# ExecutionPolicy = []
# ExposureNotification = []
# ExtensionFoundation = []
# ExtensionKit = []
# ExternalAccessory = []
# Family Controls = []
# FileProvider = []
# FileProviderUI = []
# FinderSync = []
# ForceFeedback = []
Foundation = ["objective-c", "objc2/foundation"]
# FWAUserLib = []
# GameController = []
# GameKit = []
# GameplayKit = []
# GLKit = []
# GLUT = []
# GroupActivities = []
# GSS = []
# HealthKit = []
# HIDDriverKit = []
# HomeKit = []
# HTTP Live Streaming = []
# Hypervisor = []
# iAd = []
# ICADevices = []
# IdentityLookup = []
# ImageCaptureCore = []
# ImageIO = []
# IMServicePlugIn = []
# InputMethodKit = []
# InstallerJS = []
# InstallerPlugins = []
# InstantMessage = []
# Intents = []
# IntentsUI = []
# IOBluetooth = []
# IOBluetoothUI = []
# IOKit = []
# IOSurface = []
# IOUSBHost = []
# iTunesLibrary = []
# JavaNativeFoundation = []
# JavaRuntimeSupport = []
# JavaScriptCore = []
# Kerberos = []
# Kernel = []
# KernelManagement = []
# LatentSemanticMapping = []
# LDAP = []
# LinkPresentation = []
# LivePhotosKit JS = []
# LocalAuthentication = []
# LocalAuthenticationEmbeddedUI = []
# MailKit = []
# ManagedSettings = []
# ManagedSettingsUI = []
# MapKit = []
# Maps Web Snapshots = []
# MediaAccessibility = []
# MediaLibrary = []
# MediaPlayer = []
# MediaSetup = []
# MediaToolbox = []
# Message UI = []
# Messages = []
# Metal = []
# MetalPerformanceShaders = []
# MetalPerformanceShadersGraph = []
# MetalFX = []
# MetalKit = []
# MetricKit = []
# MLCompute = []
# ModelIO = []
# MultipeerConnectivity = []
# MusicKit = []
# NaturalLanguage = []
# NearbyInteraction = []
# NetFS = []
# Network = []
# NetworkExtension = []
# NetworkingDriverKit = []
# NewsstandKit = []
# NotificationCenter = []
# OpenAL = []
# OpenCL = []
# OpenDirectory = []
# OpenGL = [] # ES?
# os = []
# OSAKit = []
# OSLog = []
# PackageDescription = []
# ParavirtualizedGraphics = []
# PassKit = []
# PCIDriverKit = []
# PCSC = []
# PDFKit = []
# PencilKit = []
# PHASE = []
# PhotoKit = []
# Photos = []
# PhotosUI = []
# Playground Bluetooth = []
# Playground Support = []
# PreferencePanes = []
# Professional Video Applications = []
# ProximityReader = []
# Push to Talk = []
# PushKit = []
# Quartz = []
# QuartzCore = [] # Core Animation
# QuickLook = []
# QuickLookThumbnailing = []
# QuickLookUI = []
# RealityKit = []
# RegexBuilder = []
# ReplayKit = []
# RoomPlan = []
# Roster API = []
# Safari app extensions = []
# SafariServices = []
# SafetyKit = []
# SceneKit = []
# ScreenCaptureKit = []
# ScreenSaver = []
# ScreenTime = []
# ScriptingBridge = []
# SCSIControllerDriverKit = []
# SCSIPeripheralsDriverKit = []
# Security = []
# SecurityFoundation = []
# SecurityInterface = []
# SensorKit = []
# SerialDriverKit = []
# ServiceManagement = []
# Shared with You = []
# ShazamKit = []
# Sign in with Apple = []
# simd = []
# Siri Event Suggestions Markup = []
# SiriKit = []
# SiriKit Cloud Media = []
# SMS and Call Reporting = []
# Social = []
# SoundAnalysis = []
# Spatial = []
# Speech = []
# SpriteKit = []
# StoreKit = []
# StoreKit Test = []
# Swift = []
# Swift Charts = []
# Swift Packages = []
# Swift Playgrounds = []
# SwiftUI = []
# System = []
# SyncServices = []
# SystemConfiguration = []
# SystemExtensions = []
# Tabular Data = []
# Tcl = []
# Technotes = []
# Thread Network = []
# TV Services = []
# TVML = []
# TVMLKit = []
# TVMLKit JS = []
# TVUIKit = []
# TWAIN = []
# UIKit = []
# UniformTypeIdentifiers = []
# USBDriverKit = []
# USBSerialDriverKit = []
# UserNotifications = []
# UserNotificationsUI = []
# VideoDecodeAcceleration = []
# VideoSubscriberAccount = []
# VideoToolbox = []
# Virtualization = []
# Vision = []
# VisionKit = []
# vmnet = []
# Wallet Orders = []
# Wallet Passes = []
# Watch Connectivity = []
# WatchKit = []
# watchOS Apps = []
# WeatherKit = []
# WeatherKit REST API = []
# WebKit = []
# WidgetKit = []
# Xcode = []
# Xcode Cloud = []
# XcodeKit = []
# xcselect = []
# XCTest = []
# XPC = []
