framework = "FSKit"
crate = "objc2-fs-kit"
required-crates = ["objc2", "objc2-foundation"]
custom-lib-rs = true
macos = "15.4"

# Uses `libc::FREAD` and `libc::FWRITE`
enum.FSVolumeOpenModes.use-value = true

# Defined in both FSVolume.h and FSVolumeHandlerResult.h
typedef.FSDirectoryVerifier.skipped = true
class.FSEnumerateDirectoryResult.methods."initWithVerifier:".skipped = true

# Wants to pass `libc::timespec` to/from objc2 methods
# (but `libc::timespec` doesn't implement `Encode`).
class.FSItemAttributes.methods.modifyTime.skipped = true
class.FSItemAttributes.methods."setModifyTime:".skipped = true
class.FSItemAttributes.methods.addedTime.skipped = true
class.FSItemAttributes.methods."setAddedTime:".skipped = true
class.FSItemAttributes.methods.changeTime.skipped = true
class.FSItemAttributes.methods."setChangeTime:".skipped = true
class.FSItemAttributes.methods.accessTime.skipped = true
class.FSItemAttributes.methods."setAccessTime:".skipped = true
class.FSItemAttributes.methods.birthTime.skipped = true
class.FSItemAttributes.methods."setBirthTime:".skipped = true
class.FSItemAttributes.methods.backupTime.skipped = true
class.FSItemAttributes.methods."setBackupTime:".skipped = true

class.FSFileName.methods."initWithCString:".arguments.0.bounds = "null-terminated"
class.FSFileName.methods."initWithBytes:length:".arguments.0.bounds.sized-by = "length"
class.FSFileName.methods."nameWithCString:".arguments.0.bounds = "null-terminated"
class.FSFileName.methods."nameWithBytes:length:".arguments.0.bounds.sized-by = "length"
