framework = "CoreMIDI"
crate = "objc2-core-midi"
# Neither objc2-foundation nor objc2-core-foundation,
# CoreMIDI is split in two parts that each use one.
required-crates = []
custom-lib-rs = true
macos = "10.0"
maccatalyst = "13.0"
ios = "4.2"
tvos = "15.0"
watchos = "8.0"
visionos = "1.0"

# Wrongly renamed (Swift's renaming algorithm is insufficient)
const.kMIDIProtocol_1_0.renamed = "Protocol_1_0"
const.kMIDIProtocol_2_0.renamed = "Protocol_2_0"

# Probably this:
fn.MIDIObjectGetStringProperty.arguments.2.lifetime = "out-pointer-not-retained"
fn.MIDIObjectGetDataProperty.arguments.2.lifetime = "out-pointer-not-retained"
fn.MIDIObjectGetDictionaryProperty.arguments.2.lifetime = "out-pointer-not-retained"
fn.MIDIObjectGetProperties.arguments.1.lifetime = "out-pointer-not-retained"
# Probably? It seems likely that this would allocate a new array.
fn.MIDIEventPacketSysexBytesForGroup.arguments.2.lifetime = "out-pointer-retained"

# Docs say: The client is responsible for releasing this CFData object when done with it.
fn.MIDISetupToData.arguments.1.lifetime = "out-pointer-retained"
# Probably:
fn.MIDIGetSerialPortOwner.arguments.1.lifetime = "out-pointer-not-retained"
# Docs say: The array should be released by the caller.
fn.MIDIGetSerialPortDrivers.arguments.0.lifetime = "out-pointer-retained"

# Fix property generics.
fn.MIDIObjectGetDictionaryProperty.arguments.2.generics = ["CoreFoundation.CFString.CFString", "CoreFoundation.CFType"]
fn.MIDIObjectSetDictionaryProperty.arguments.2.generics = ["CoreFoundation.CFString.CFString", "CoreFoundation.CFType"]
fn.MIDIGetSerialPortDrivers.arguments.0.generics = ["CoreFoundation.CFString.CFString"]
