framework = "DataDetection"
crate = "objc2-data-detection"
required-dependencies = ["objc2-foundation"]
macos = "12.0"
maccatalyst = "15.0"
ios = "15.0"
tvos = "15.0"
watchos = "8.0"
visionos = "1.0"
