framework = "CoreMedia"
crate = "objc2-core-media"
required-crates = ["objc2-core-foundation"]
custom-lib-rs = true
macos = "10.7"
maccatalyst = "13.1"
ios = "4.0"
tvos = "9.0"
watchos = "6.0"
visionos = "1.0"

# Differing definitions depending on architecture
typedef.CMBaseClassVersion.skipped = true
typedef.CMStructVersion.skipped = true

# Used to better support older versions that didn't expose the symbol, but redundant nowadays.
const.kCMFormatDescriptionExtension_VerbatimImageDescription.skipped = true

# Depends on CFTimeInterval and CFAbsoluteTime without feature gating.
const.kCMTimebaseVeryLongCFTimeInterval.skipped = true
const.kCMTimebaseFarFutureCFAbsoluteTime.skipped = true

# Naming conflicts with the newer Copy variants.
fn.CMBufferQueueGetHead.renamed = "get_head"
fn.CMTimebaseGetMasterTimebase.renamed = "get_master_timebase"
fn.CMTimebaseGetMasterClock.renamed = "get_master_clock"
fn.CMTimebaseGetMaster.renamed = "get_master"
fn.CMTimebaseGetUltimateMasterClock.renamed = "get_ultimate_master_clock"

# Doesn't use usual "Make" terminology
fn.CMSampleBufferMakeDataReady.renamed = "make_data_ready"
fn.CMClockMakeHostTimeFromSystemUnits.renamed = "make_host_time_from_system_units"

# Translated as "new_empty", but it's common in Rust to just use "empty".
fn.CMTimeMappingMakeEmpty.renamed = "empty"

# Fix weird naming with "retain" in it.
fn.CMBufferQueueDequeueAndRetain.arguments.0.bounds = "single"
fn.CMBufferQueueDequeueAndRetain.renamed = "dequeue"
fn.CMBufferQueueDequeueIfDataReadyAndRetain.arguments.0.bounds = "single"
fn.CMBufferQueueDequeueIfDataReadyAndRetain.renamed = "dequeue_if_data_ready"

##
## Generics
##

# Intentionally opaque
fn.CMTimeCopyAsDictionary.return.generics = []
fn.CMTimeMakeFromDictionary.arguments.0.generics = []
fn.CMTimeRangeCopyAsDictionary.return.generics = []
fn.CMTimeRangeMakeFromDictionary.arguments.0.generics = []
fn.CMTimeMappingCopyAsDictionary.return.generics = []
fn.CMTimeMappingMakeFromDictionary.arguments.0.generics = []
fn.CMTagCopyAsDictionary.return.generics = []
fn.CMTagMakeFromDictionary.arguments.0.generics = []
fn.CMTagCollectionCopyAsDictionary.return.generics = []
fn.CMTagCollectionCreateFromDictionary.arguments.0.generics = []

fn.CMFormatDescriptionCreate.arguments.3.generics = ["CoreFoundation.CFString.CFString", "CoreFoundation.CFPropertyList.CFPropertyList"]
fn.CMFormatDescriptionGetExtensions.return.generics = ["CoreFoundation.CFString.CFString", "CoreFoundation.CFPropertyList.CFPropertyList"]
fn.CMAudioFormatDescriptionCreate.arguments.6.generics = ["CoreFoundation.CFString.CFString", "CoreFoundation.CFPropertyList.CFPropertyList"]
fn.CMAudioFormatDescriptionCreateSummary.arguments.1.generics = ["CoreMedia.CMFormatDescription.CMAudioFormatDescription"]
fn.CMVideoFormatDescriptionCreate.arguments.4.generics = ["CoreFoundation.CFString.CFString", "CoreFoundation.CFPropertyList.CFPropertyList"]
fn.CMVideoFormatDescriptionCreateFromHEVCParameterSets.arguments.5.generics = ["CoreFoundation.CFString.CFString", "CoreFoundation.CFPropertyList.CFPropertyList"]
fn.CMVideoFormatDescriptionGetExtensionKeysCommonWithImageBuffers.return.generics = ["CoreFoundation.CFString.CFString"]
fn.CMVideoFormatDescriptionCopyTagCollectionArray.arguments.1.generics = ["CoreMedia.CMTagCollection.CMTagCollection"]
fn.CMMuxedFormatDescriptionCreate.arguments.2.generics = ["CoreFoundation.CFString.CFString", "CoreFoundation.CFPropertyList.CFPropertyList"]
fn.CMTimeCodeFormatDescriptionCreate.arguments.5.generics = ["CoreFoundation.CFString.CFString", "CoreFoundation.CFPropertyList.CFPropertyList"]
fn.CMMetadataFormatDescriptionCreateWithKeys.arguments.2.generics = ["CoreFoundation.CFDictionary.CFDictionary<CoreFoundation.CFString.CFString, CoreFoundation.CFType>"]
fn.CMMetadataFormatDescriptionCreateWithMetadataSpecifications.arguments.2.generics = ["CoreFoundation.CFDictionary.CFDictionary<CoreFoundation.CFString.CFString, CoreFoundation.CFType>"]
fn.CMMetadataFormatDescriptionCreateWithMetadataFormatDescriptionAndMetadataSpecifications.arguments.2.generics = ["CoreFoundation.CFDictionary.CFDictionary<CoreFoundation.CFString.CFString, CoreFoundation.CFType>"]
fn.CMMetadataFormatDescriptionGetKeyWithLocalID.return.generics = ["CoreFoundation.CFString.CFString", "CoreFoundation.CFType"]
fn.CMMetadataFormatDescriptionGetIdentifiers.return.generics = ["CoreFoundation.CFString.CFString"] # I think

fn.CMCopyDictionaryOfAttachments.return.generics = ["CoreFoundation.CFString.CFString", "CoreFoundation.CFType"]
fn.CMSetAttachments.arguments.1.generics = ["CoreFoundation.CFString.CFString", "CoreFoundation.CFType"]

fn.CMSampleBufferGetSampleAttachmentsArray.return.generics = ["CoreFoundation.CFDictionary.CFDictionary<CoreFoundation.CFString.CFString, CoreFoundation.CFType>"]

fn.CMTaggedBufferGroupCreate.arguments.1.generics = ["CoreMedia.CMTagCollection.CMTagCollection"]
fn.CMTaggedBufferGroupCreate.arguments.2.generics = ["CoreFoundation.CFType"] # CMSampleBuffer or CVPixelBuffer
fn.CMTaggedBufferGroupCreateCombined.arguments.1.generics = ["CoreMedia.CMTaggedBufferGroup.CMTaggedBufferGroup"]
fn.CMTaggedBufferGroupFormatDescriptionCreateForTaggedBufferGroupWithExtensions.arguments.2.generics = ["CoreFoundation.CFString.CFString", "CoreFoundation.CFPropertyList.CFPropertyList"]

fn.CMMemoryPoolCreate.arguments.0.generics = ["CoreFoundation.CFString.CFString", "CoreFoundation.CFType"]

fn.CMMetadataDataTypeRegistryRegisterDataType.arguments.2.generics = ["CoreFoundation.CFString.CFString"]
fn.CMMetadataDataTypeRegistryGetConformingDataTypes.return.generics = ["CoreFoundation.CFString.CFString"]
fn.CMMetadataDataTypeRegistryGetBaseDataTypes.return.generics = ["CoreFoundation.CFString.CFString"]

##
## Pointer bounds
##

fn.CMAudioFormatDescriptionCreate.arguments.1.bounds = "single"
fn.CMAudioFormatDescriptionCreate.arguments.3.bounds.sized-by = "layout_size"
fn.CMAudioFormatDescriptionGetStreamBasicDescription.return.bounds = "single"
fn.CMAudioFormatDescriptionGetMagicCookie.arguments.1.bounds = "single"
fn.CMAudioFormatDescriptionGetMagicCookie.return.bounds.sized-by = "*size_out"
fn.CMAudioFormatDescriptionGetChannelLayout.arguments.1.bounds = "single"
fn.CMAudioFormatDescriptionGetChannelLayout.return.bounds.sized-by = "*size_out"
fn.CMAudioFormatDescriptionGetFormatList.arguments.1.bounds = "single"
fn.CMAudioFormatDescriptionGetFormatList.return.bounds.sized-by = "*size_out"
fn.CMAudioFormatDescriptionGetRichestDecodableFormat.return.bounds = "single"
fn.CMAudioFormatDescriptionGetMostCompatibleFormat.return.bounds = "single"
fn.CMAudioFormatDescriptionEqual.arguments.3.bounds = "single"

fn.CMVideoFormatDescriptionCreateFromH264ParameterSets.arguments.2.bounds.counted-by = "parameter_set_count"
fn.CMVideoFormatDescriptionCreateFromH264ParameterSets.arguments.3.bounds.counted-by = "parameter_set_count"
fn.CMVideoFormatDescriptionCreateFromHEVCParameterSets.arguments.2.bounds.counted-by = "parameter_set_count"
fn.CMVideoFormatDescriptionCreateFromHEVCParameterSets.arguments.3.bounds.counted-by = "parameter_set_count"
fn.CMVideoFormatDescriptionGetH264ParameterSetAtIndex.arguments.2.bounds = "single"
fn.CMVideoFormatDescriptionGetH264ParameterSetAtIndex.arguments.3.bounds = "single"
fn.CMVideoFormatDescriptionGetH264ParameterSetAtIndex.arguments.4.bounds = "single"
fn.CMVideoFormatDescriptionGetH264ParameterSetAtIndex.arguments.5.bounds = "single"
fn.CMVideoFormatDescriptionGetHEVCParameterSetAtIndex.arguments.2.bounds = "single"
fn.CMVideoFormatDescriptionGetHEVCParameterSetAtIndex.arguments.3.bounds = "single"
fn.CMVideoFormatDescriptionGetHEVCParameterSetAtIndex.arguments.4.bounds = "single"
fn.CMVideoFormatDescriptionGetHEVCParameterSetAtIndex.arguments.5.bounds = "single"
fn.CMTextFormatDescriptionGetDisplayFlags.arguments.1.bounds = "single"
fn.CMTextFormatDescriptionGetJustification.arguments.1.bounds = "single"
fn.CMTextFormatDescriptionGetJustification.arguments.2.bounds = "single"
fn.CMTextFormatDescriptionGetDefaultTextBox.arguments.3.bounds = "single"
fn.CMTextFormatDescriptionGetDefaultStyle.arguments.1.bounds = "single"
fn.CMTextFormatDescriptionGetDefaultStyle.arguments.2.bounds = "single"
fn.CMTextFormatDescriptionGetDefaultStyle.arguments.3.bounds = "single"
fn.CMTextFormatDescriptionGetDefaultStyle.arguments.4.bounds = "single"
fn.CMTextFormatDescriptionGetDefaultStyle.arguments.5.bounds = "single"
fn.CMTextFormatDescriptionGetDefaultStyle.arguments.6.bounds = "single"

fn.CMVideoFormatDescriptionCreateFromBigEndianImageDescriptionData.arguments.1.bounds.sized-by = "size"
fn.CMSwapBigEndianImageDescriptionToHost.arguments.0.bounds.sized-by = "image_description_size"
fn.CMSwapHostEndianImageDescriptionToBig.arguments.0.bounds.sized-by = "image_description_size"
fn.CMAudioFormatDescriptionCreateFromBigEndianSoundDescriptionData.arguments.1.bounds.sized-by = "size"
fn.CMSwapBigEndianSoundDescriptionToHost.arguments.0.bounds.sized-by = "sound_description_size"
fn.CMSwapHostEndianSoundDescriptionToBig.arguments.0.bounds.sized-by = "sound_description_size"
fn.CMTextFormatDescriptionCreateFromBigEndianTextDescriptionData.arguments.1.bounds.sized-by = "size"
fn.CMSwapBigEndianTextDescriptionToHost.arguments.0.bounds.sized-by = "text_description_size"
fn.CMSwapHostEndianTextDescriptionToBig.arguments.0.bounds.sized-by = "text_description_size"
fn.CMClosedCaptionFormatDescriptionCreateFromBigEndianClosedCaptionDescriptionData.arguments.1.bounds.sized-by = "size"
fn.CMSwapBigEndianClosedCaptionDescriptionToHost.arguments.0.bounds.sized-by = "closed_caption_description_size"
fn.CMSwapHostEndianClosedCaptionDescriptionToBig.arguments.0.bounds.sized-by = "closed_caption_description_size"
fn.CMTimeCodeFormatDescriptionCreateFromBigEndianTimeCodeDescriptionData.arguments.1.bounds.sized-by = "size"
fn.CMSwapBigEndianTimeCodeDescriptionToHost.arguments.0.bounds.sized-by = "time_code_description_size"
fn.CMSwapHostEndianTimeCodeDescriptionToBig.arguments.0.bounds.sized-by = "time_code_description_size"
fn.CMMetadataFormatDescriptionCreateFromBigEndianMetadataDescriptionData.arguments.1.bounds.sized-by = "size"
fn.CMSwapBigEndianMetadataDescriptionToHost.arguments.0.bounds.sized-by = "metadata_description_size"
fn.CMSwapHostEndianMetadataDescriptionToBig.arguments.0.bounds.sized-by = "metadata_description_size"

fn.CMGetAttachment.arguments.2.bounds = "single"

fn.CMBlockBufferCreateWithMemoryBlock.arguments.4.bounds = "single"
fn.CMBlockBufferCreateContiguous.arguments.3.bounds = "single"
fn.CMBlockBufferAppendMemoryBlock.arguments.4.bounds = "single"
fn.CMBlockBufferAccessDataBytes.arguments.3.bounds.sized-by = "length"
fn.CMBlockBufferAccessDataBytes.arguments.4.bounds = "single"
fn.CMBlockBufferCopyDataBytes.arguments.3.bounds.sized-by = "data_length"
fn.CMBlockBufferGetDataPointer.arguments.2.bounds = "single"
fn.CMBlockBufferGetDataPointer.arguments.3.bounds = "single"
fn.CMBlockBufferGetDataPointer.arguments.4.bounds = "single"

fn.CMBufferQueueGetCallbacksForUnsortedSampleBuffers.return.bounds = "single"
fn.CMBufferQueueGetCallbacksForSampleBuffersSortedByOutputPTS.return.bounds = "single"
fn.CMBufferQueueCreate.arguments.2.bounds = "single"
fn.CMBufferQueueCreateWithHandlers.arguments.2.bounds = "single"
fn.CMBufferQueueInstallTrigger.arguments.5.bounds = "single"
fn.CMBufferQueueInstallTriggerWithIntegerThreshold.arguments.5.bounds = "single"
fn.CMBufferQueueInstallTriggerHandler.arguments.3.bounds = "single"
fn.CMBufferQueueInstallTriggerHandlerWithIntegerThreshold.arguments.3.bounds = "single"

fn.CMSampleBufferCreate.arguments.8.bounds.counted-by = "num_sample_timing_entries"
fn.CMSampleBufferCreate.arguments.10.bounds.counted-by = "num_sample_size_entries"
fn.CMSampleBufferCreateWithMakeDataReadyHandler.arguments.6.bounds.counted-by = "num_sample_timing_entries"
fn.CMSampleBufferCreateWithMakeDataReadyHandler.arguments.8.bounds.counted-by = "num_sample_size_entries"
fn.CMSampleBufferCreateReady.arguments.5.bounds.counted-by = "num_sample_timing_entries"
fn.CMSampleBufferCreateReady.arguments.7.bounds.counted-by = "num_sample_size_entries"
fn.CMSampleBufferCreateForImageBuffer.arguments.6.bounds = "single"
fn.CMSampleBufferCreateForImageBufferWithMakeDataReadyHandler.arguments.4.bounds = "single"
fn.CMSampleBufferCreateReadyWithImageBuffer.arguments.3.bounds = "single"
fn.CMSampleBufferCreateCopyWithNewTiming.arguments.3.bounds.counted-by = "num_sample_timing_entries"
fn.CMSampleBufferSetDataBufferFromAudioBufferList.arguments.4.bounds = "single"
fn.CMSampleBufferGetAudioBufferListWithRetainedBlockBuffer.arguments.1.bounds = "single"
fn.CMSampleBufferGetAudioBufferListWithRetainedBlockBuffer.arguments.2.bounds = "unsafe" # AudioBufferList sized by buffer_list_size somehow
fn.CMSampleBufferGetAudioStreamPacketDescriptions.arguments.2.bounds = "unsafe" # AudioBufferList sized by packet_descriptions_size somehow
fn.CMSampleBufferGetAudioStreamPacketDescriptions.arguments.3.bounds = "single"
fn.CMSampleBufferGetAudioStreamPacketDescriptionsPtr.arguments.1.bounds = "single"
fn.CMSampleBufferGetAudioStreamPacketDescriptionsPtr.arguments.2.bounds = "single"
fn.CMSampleBufferCopyPCMDataIntoAudioBufferList.arguments.3.bounds = "unsafe" # AudioBufferList must be correctly sized
fn.CMSampleBufferHasDataFailed.arguments.1.bounds = "single"
fn.CMSampleBufferGetSampleTimingInfoArray.arguments.2.bounds.counted-by = "num_sample_timing_entries"
fn.CMSampleBufferGetSampleTimingInfoArray.arguments.3.bounds = "single"
fn.CMSampleBufferGetOutputSampleTimingInfoArray.arguments.2.bounds.counted-by = "timing_array_entries"
fn.CMSampleBufferGetOutputSampleTimingInfoArray.arguments.3.bounds = "single"
fn.CMSampleBufferGetSampleTimingInfo.arguments.2.bounds = "single"
fn.CMSampleBufferGetSampleSizeArray.arguments.2.bounds.counted-by = "size_array_entries"
fn.CMSampleBufferGetSampleSizeArray.arguments.3.bounds = "single"
fn.CMAudioSampleBufferCreateWithPacketDescriptions.arguments.8.bounds.counted-by = "num_samples"
fn.CMAudioSampleBufferCreateWithPacketDescriptionsAndMakeDataReadyHandler.arguments.6.bounds.counted-by = "num_samples"
fn.CMAudioSampleBufferCreateReadyWithPacketDescriptions.arguments.5.bounds.counted-by = "num_samples"

fn.CMTagCollectionCreate.arguments.1.bounds.counted-by = "tag_count"
fn.CMTagCollectionContainsSpecifiedTags.arguments.1.bounds.counted-by = "contained_tag_count"
fn.CMTagCollectionGetTags.arguments.1.bounds.counted-by = "tag_buffer_count"
fn.CMTagCollectionGetTags.arguments.3.bounds = "single"
fn.CMTagCollectionGetTagsWithCategory.arguments.2.bounds.counted-by = "tag_buffer_count"
fn.CMTagCollectionGetTagsWithCategory.arguments.4.bounds = "single"
fn.CMTagCollectionGetTagsWithFilterFunction.arguments.1.bounds.counted-by = "tag_buffer_count"
fn.CMTagCollectionGetTagsWithFilterFunction.arguments.3.bounds = "single"
fn.CMTagCollectionCopyTagsOfCategories.arguments.2.bounds.counted-by = "categories_count"
fn.CMTagCollectionAddTagsFromArray.arguments.1.bounds.counted-by = "tag_count"

fn.CMTaggedBufferGroupGetCVPixelBufferForTag.arguments.2.bounds = "single"
fn.CMTaggedBufferGroupGetCVPixelBufferForTagCollection.arguments.2.bounds = "single"
fn.CMTaggedBufferGroupGetCMSampleBufferForTag.arguments.2.bounds = "single"
fn.CMTaggedBufferGroupGetCMSampleBufferForTagCollection.arguments.2.bounds = "single"

fn.CMClockGetAnchorTime.arguments.1.bounds = "single"
fn.CMClockGetAnchorTime.arguments.2.bounds = "single"
fn.CMTimebaseGetTimeAndRate.arguments.1.bounds = "single"
fn.CMTimebaseGetTimeAndRate.arguments.2.bounds = "single"
fn.CMSyncGetRelativeRateAndAnchorTime.arguments.2.bounds = "single"
fn.CMSyncGetRelativeRateAndAnchorTime.arguments.3.bounds = "single"
fn.CMSyncGetRelativeRateAndAnchorTime.arguments.4.bounds = "single"

fn.CMAudioDeviceClockGetAudioDevice.arguments.2.bounds = "single"
fn.CMAudioDeviceClockGetAudioDevice.arguments.3.bounds = "single"
