framework = "Darwin"
crate = "libc2"
required-crates = []
link = false
modulemap = "usr/include/Darwin.modulemap"
is-library = true

module.Mach.skipped = true

# Available everywhere
macos = "10.0"
maccatalyst = "13.0"
ios = "2.0"
tvos = "9.0"
watchos = "2.0"
visionos = "1.0"
gnustep = true

# HACK: Define `task_port_t` in the using crate (it's a simple alias to `task_t`).
external.task_port_t.module = "__builtin__"

# Definition fails formatting
static.NDR_record.skipped = true
fn.box.skipped = true
fn.move.skipped = true
