framework = "UIKit"
crate = "objc2-ui-kit"
required-crates = ["objc2", "objc2-foundation"]
custom-lib-rs = true
maccatalyst = "13.0"
ios = "2.0"
tvos = "9.0"
watchos = "2.0"
visionos = "1.0"

external.INIntent.module = "Intents.INIntent"
external.UTType.module = "UniformTypeIdentifiers.UTType"
external.CKContainer.module = "CloudKit.CKContainer"
external.CKShare.module = "CloudKit.CKShare"
external.CKShareMetadata.module = "CloudKit.CKShareMetadata"
external.NSManagedObjectContext.module = "CoreData.NSManagedObjectContext"
external.NSManagedObjectModel.module = "CoreData.NSManagedObjectModel"
external.CLRegion.module = "CoreLocation.CLRegion"

# CF_RETURNS_NOT_RETAINED
fn.UIGraphicsGetCurrentContext.skipped = true

# Both property and method
class.NSDiffableDataSourceSectionSnapshot.methods.items.skipped = true

# Duplicated static
static.UIKeyInputF1.skipped = true

# These protocol impls would return the wrong types
class.NSTextStorage.skipped-protocols = ["NSCopying", "NSMutableCopying"]

# Set counterparts
class.NSParagraphStyle.counterpart = "MutableSubclass(UIKit.NSParagraphStyle.NSMutableParagraphStyle)"
class.NSMutableParagraphStyle.counterpart = "ImmutableSuperclass(UIKit.NSParagraphStyle.NSParagraphStyle)"
class.UIApplicationShortcutItem.counterpart = "MutableSubclass(UIKit.UIApplicationShortcutItem.UIMutableApplicationShortcutItem)"
class.UIMutableApplicationShortcutItem.counterpart = "ImmutableSuperclass(UIKit.UIApplicationShortcutItem.UIApplicationShortcutItem)"
class.UIUserNotificationCategory.counterpart = "MutableSubclass(UIKit.UIUserNotificationSettings.UIMutableUserNotificationCategory)"
class.UIMutableUserNotificationCategory.counterpart = "ImmutableSuperclass(UIKit.UIUserNotificationSettings.UIUserNotificationCategory)"
class.UIUserNotificationAction.counterpart = "MutableSubclass(UIKit.UIUserNotificationSettings.UIMutableUserNotificationAction)"
class.UIMutableUserNotificationAction.counterpart = "ImmutableSuperclass(UIKit.UIUserNotificationSettings.UIUserNotificationAction)"

# These subclass a generic struct, and hence the type parameter defaults to
# `AnyObject`, which is not PartialEq, Eq nor Hash.
class.NSLayoutXAxisAnchor.derives = "Debug"
class.NSLayoutYAxisAnchor.derives = "Debug"
class.NSLayoutDimension.derives = "Debug"

# Different definitions depending on target
enum.NSImageResizingMode.skipped = true
enum.NSTextAlignment.skipped = true

# Duplicated parameter name
class.UIStepper.methods."dividerImageForLeftSegmentState:rightSegmentState:".skipped = true

# `UITrait` is kinda weird, it's a typedef to a generic on `AnyClass`
class.UITraitCollection.methods."changedTraitsFromTraitCollection:".skipped = true
class.UITraitCollection.methods.systemTraitsAffectingColorAppearance.skipped = true
class.UITraitCollection.methods.systemTraitsAffectingImageLookup.skipped = true
protocol.UITraitChangeObservable.methods."registerForTraitChanges:withHandler:".skipped = true
protocol.UITraitChangeObservable.methods."registerForTraitChanges:withTarget:action:".skipped = true
protocol.UITraitChangeObservable.methods."registerForTraitChanges:withAction:".skipped = true

# Duplicate properties
class.UIApplication.methods.statusBarStyle.skipped = true
class.UIApplication.methods.isStatusBarHidden.skipped = true
class.UIApplication.methods.statusBarOrientation.skipped = true
class.UIGestureRecognizer.methods.state.skipped = true

# Not allowed by orphan rules
class.NSAttributedString.skipped-protocols = ["NSItemProviderReading", "NSItemProviderWriting"]
class.NSUserActivity.skipped-protocols = ["NSItemProviderReading", "NSItemProviderWriting"]

# Requires MainThreadOnly, which I'm not sure UIImage is?
class.UIImage.skipped-protocols = ["UIItemProviderPresentationSizeProviding", "UIAccessibilityIdentification"]

# Requires MainThreadOnly, which I'm not sure NSTextAttachment is?
class.NSTextAttachment.skipped-protocols = ["UIAccessibilityContentSizeCategoryImageAdjusting"]

# Typedef to an enum, which our values handle wrong
typedef.UITextWritingDirection.skipped = true
static.UITextWritingDirectionNatural.skipped = true
static.UITextWritingDirectionLeftToRight.skipped = true
static.UITextWritingDirectionRightToLeft.skipped = true

# Needs `AVAudioSession` (undesired dependency)
class.UIScene.methods."getDefaultAudioSessionWithCompletionHandler:".skipped = true

# Needs `INIntent`
protocol.UIApplicationDelegate.methods."application:handlerForIntent:".skipped = true
protocol.UIApplicationDelegate.methods."application:handleIntent:completionHandler:".skipped = true

# Needs `CTTextAlignment`
fn.NSTextAlignmentToCTTextAlignment.skipped = true
fn.NSTextAlignmentFromCTTextAlignment.skipped = true

# Needs LinkPresentation, which itself depends on UIKit
protocol.UIActivityItemSource.methods."activityViewControllerLinkMetadata:".skipped = true
class.UIDocumentProperties.methods."initWithMetadata:".skipped = true
class.UIDocumentProperties.methods.metadata.skipped = true
class.UIDocumentProperties.methods."setMetadata:".skipped = true

# Unclear how error handling is done for methods returning integers
class.UIApplication.methods."defaultStatusForCategory:error:".skipped = true

# Protocols require that these are main thread only
class.UIDocumentBrowserTransitionController.main-thread-only = true
class.UIDocumentInteractionController.main-thread-only = true
class.UIToolTipInteraction.main-thread-only = true
class.UIWindowSceneActivationInteraction.main-thread-only = true
class.UITraitUserInterfaceIdiom.main-thread-only = true
class.UITraitUserInterfaceStyle.main-thread-only = true
class.UITraitLayoutDirection.main-thread-only = true
class.UITraitDisplayScale.main-thread-only = true
class.UITraitHorizontalSizeClass.main-thread-only = true
class.UITraitVerticalSizeClass.main-thread-only = true
class.UITraitForceTouchCapability.main-thread-only = true
class.UITraitPreferredContentSizeCategory.main-thread-only = true
class.UITraitDisplayGamut.main-thread-only = true
class.UITraitAccessibilityContrast.main-thread-only = true
class.UITraitUserInterfaceLevel.main-thread-only = true
class.UITraitLegibilityWeight.main-thread-only = true
class.UITraitActiveAppearance.main-thread-only = true
class.UITraitToolbarItemPresentationSize.main-thread-only = true
class.UITraitImageDynamicRange.main-thread-only = true
class.UITraitTypesettingLanguage.main-thread-only = true
class.UITraitSceneCaptureState.main-thread-only = true
class.UITraitListEnvironment.main-thread-only = true

# We don't really want objc2-ui-kit to depend on objc2-core-text
class.NSAdaptiveImageGlyph.skipped-protocols = ["CTAdaptiveImageProviding"]

# Needs `INPerson`
protocol.UIActivityItemSource.methods."activityViewControllerShareRecipients:".skipped = true

# Custom-defined.
fn.UIApplicationMain.renamed = "__main"

###
### Safety
###
### Methods used in Winit, marked safe mostly for convenience there.
###

class.UIApplication.methods.windows.unsafe = false
class.UIApplication.methods.sharedApplication.unsafe = false
class.UIApplication.methods.statusBarFrame.unsafe = false
protocol.UICoordinateSpace.methods."convertPoint:toCoordinateSpace:".unsafe = false
protocol.UICoordinateSpace.methods."convertPoint:fromCoordinateSpace:".unsafe = false
protocol.UICoordinateSpace.methods."convertRect:toCoordinateSpace:".unsafe = false
protocol.UICoordinateSpace.methods."convertRect:fromCoordinateSpace:".unsafe = false
protocol.UICoordinateSpace.methods.bounds.unsafe = false
class.UIDevice.methods.currentDevice.unsafe = false
class.UIDevice.methods.userInterfaceIdiom.unsafe = false
class.UIGestureRecognizer.methods.delegate.unsafe = false
class.UIGestureRecognizer.methods."setDelegate:".unsafe = false
class.UIPanGestureRecognizer.methods.maximumNumberOfTouches.unsafe = false
class.UIPanGestureRecognizer.methods."setMaximumNumberOfTouches:".unsafe = false
class.UIPanGestureRecognizer.methods.minimumNumberOfTouches.unsafe = false
class.UIPanGestureRecognizer.methods."setMinimumNumberOfTouches:".unsafe = false
class.UIPanGestureRecognizer.methods."translationInView:".unsafe = false
class.UIPanGestureRecognizer.methods."setTranslation:inView:".unsafe = false
class.UIPanGestureRecognizer.methods."velocityInView:".unsafe = false
class.UIPanGestureRecognizer.methods.allowedScrollTypesMask.unsafe = false
class.UIPinchGestureRecognizer.methods.scale.unsafe = false
class.UIPinchGestureRecognizer.methods.velocity.unsafe = false
# UIResponder
class.UIRotationGestureRecognizer.methods.rotation.unsafe = false
class.UIRotationGestureRecognizer.methods.velocity.unsafe = false
class.UITapGestureRecognizer.methods.buttonMaskRequired.unsafe = false
class.UITapGestureRecognizer.methods."setButtonMaskRequired:".unsafe = false
class.UITapGestureRecognizer.methods.numberOfTapsRequired.unsafe = false
class.UITapGestureRecognizer.methods."setNumberOfTapsRequired:".unsafe = false
class.UITapGestureRecognizer.methods.numberOfTouchesRequired.unsafe = false
class.UITapGestureRecognizer.methods."setNumberOfTouchesRequired:".unsafe = false
class.UIScreen.methods.mainScreen.unsafe = false
class.UIScreen.methods.screens.unsafe = false
class.UIScreen.methods.mirroredScreen.unsafe = false
class.UIScreen.methods.nativeBounds.unsafe = false
class.UIScreen.methods.nativeScale.unsafe = false
class.UIScreen.methods.preferredMode.unsafe = false
class.UIScreen.methods.maximumFramesPerSecond.unsafe = false
class.UIScreen.methods.currentMode.unsafe = false
class.UIScreen.methods.availableModes.unsafe = false
class.UIScreen.methods."setCurrentMode:".unsafe = false
class.UIScreen.methods.bounds.unsafe = false
class.UIScreen.methods.scale.unsafe = false
class.UIScreen.methods.overscanCompensation.unsafe = false
class.UIScreen.methods."setOverscanCompensation:".unsafe = false
class.UIScreen.methods.coordinateSpace.unsafe = false
class.UIScreenMode.methods.size.unsafe = false
class.UITraitCollection.methods.forceTouchCapability.unsafe = false
protocol.UITraitEnvironment.methods.traitCollection.unsafe = false
class.UITouch.methods."locationInView:".unsafe = false
class.UITouch.methods."previousLocationInView:".unsafe = false
class.UITouch.methods.view.unsafe = false
class.UITouch.methods.window.unsafe = false
class.UITouch.methods.tapCount.unsafe = false
class.UITouch.methods.timestamp.unsafe = false
class.UITouch.methods.type.unsafe = false
class.UITouch.methods.phase.unsafe = false
class.UITouch.methods.force.unsafe = false
class.UITouch.methods.maximumPossibleForce.unsafe = false
class.UITouch.methods.altitudeAngle.unsafe = false
class.UITouch.methods."azimuthAngleInView:".unsafe = false
class.UITouch.methods."azimuthUnitVectorInView:".unsafe = false
class.UITouch.methods.rollAngle.unsafe = false
class.UIView.methods."initWithFrame:".unsafe = false
class.UIView.methods.backgroundColor.unsafe = false
class.UIView.methods."setBackgroundColor:".unsafe = false
class.UIView.methods.layerClass.unsafe = false
class.UIView.methods.layer.unsafe = false
class.UIView.methods.frame.unsafe = false
class.UIView.methods."setFrame:".unsafe = false
class.UIView.methods.bounds.unsafe = false
class.UIView.methods."setBounds:".unsafe = false
class.UIView.methods.superview.unsafe = false
class.UIView.methods.subviews.unsafe = false
class.UIView.methods.window.unsafe = false
class.UIView.methods.multipleTouchEnabled.unsafe = false
class.UIView.methods."setMultipleTouchEnabled:".unsafe = false
class.UIView.methods.contentScaleFactor.unsafe = false
class.UIView.methods."setContentScaleFactor:".unsafe = false
class.UIView.methods."addGestureRecognizer:".unsafe = false
class.UIView.methods."removeGestureRecognizer:".unsafe = false
class.UIView.methods.gestureRecognizers.unsafe = false
class.UIView.methods."gestureRecognizerShouldBegin:".unsafe = false
class.UIView.methods.isHidden.unsafe = false
class.UIView.methods."setHidden:".unsafe = false
class.UIView.methods.setNeedsDisplay.unsafe = false
class.UIView.methods.safeAreaInsets.unsafe = false
class.UIViewController.methods.attemptRotationToDeviceOrientation.unsafe = false
class.UIViewController.methods.setNeedsStatusBarAppearanceUpdate.unsafe = false
class.UIViewController.methods.setNeedsUpdateOfHomeIndicatorAutoHidden.unsafe = false
class.UIViewController.methods.setNeedsUpdateOfScreenEdgesDeferringSystemGestures.unsafe = false
class.UIViewController.methods.view.unsafe = false
class.UIViewController.methods."setView:".unsafe = false
class.UIWindow.methods.screen.unsafe = false
class.UIWindow.methods."setScreen:".unsafe = false
class.UIWindow.methods.rootViewController.unsafe = false
class.UIWindow.methods."setRootViewController:".unsafe = false
class.UIWindow.methods.makeKeyAndVisible.unsafe = false
class.UIWindow.methods.isKeyWindow.unsafe = false
