[package]
name = "objc-sys"
# Remember to update `html_root_url` in lib.rs, the `links` key, and the
# exception function name.
version = "0.2.0-beta.2"
authors = ["Mads Marquart <mads@marquart.dk>"]
edition = "2021"

description = "Raw bindings to the Objective-C runtime and ABI"
keywords = ["objective-c", "macos", "ios", "objc_msgSend", "sys"]
categories = [
    "external-ffi-bindings",
    # "no_std" # TODO
    "os::macos-apis",
]
repository = "https://github.com/madsmtm/objc2"
documentation = "https://docs.rs/objc-sys/"
license = "MIT"

readme = "README.md"

# Downstream users can customize the linking to libobjc!
# See https://doc.rust-lang.org/cargo/reference/build-scripts.html#overriding-build-scripts
links = "objc_0_2"
build = "build.rs"

[features]
# The default runtime is Apple's. Other platforms will probably error if the
# correct feature flag is not specified.
default = ["std", "apple"]

# Currently not possible to turn off, put here for forwards compatibility.
std = ["alloc"]
alloc = []

# Link to Apple's objc4
apple = []

# Link to GNUStep's libobjc2
gnustep-1-7 = []
gnustep-1-8 = ["gnustep-1-7"]
gnustep-1-9 = ["gnustep-1-8"]
gnustep-2-0 = ["gnustep-1-9"]
gnustep-2-1 = ["gnustep-2-0"]

# Link to Microsoft's libobjc2
unstable-winobjc = ["gnustep-1-8"]

# Link to ObjFW
unstable-objfw = []

# Use nightly c_unwind feature
unstable-c-unwind = []

# Private
unstable-exception = ["cc"]
unstable-docsrs = []

[build-dependencies]
cc = { version = "1", optional = true }

[package.metadata.docs.rs]
default-target = "x86_64-apple-darwin"
no-default-features = true
features = ["std", "unstable-docsrs"]

targets = [
    # MacOS
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    # "i686-apple-darwin",
    # iOS
    "aarch64-apple-ios",
    "x86_64-apple-ios",
    # "armv7-apple-ios",
    # "i386-apple-ios",
    # GNUStep
    "x86_64-unknown-linux-gnu",
    "i686-unknown-linux-gnu",
    # Windows
    "x86_64-pc-windows-msvc",
]
