[package]
name = "examples-app"
version = "0.0.0"
edition = "2021"
license = "Zlib OR Apache-2.0 OR MIT"
publish = false

[[example]]
name = "delegate"
path = "delegate.rs"

[[example]]
name = "default_xcode_app"
path = "default_xcode_app/main.rs"

# The example from `objc2`'s main docs.
[[example]]
name = "hello_world_app"
path = "hello_world_app.rs"

[[example]]
name = "memory_pressure"
path = "memory_pressure.rs"

[features]
unstable-darwin-objc = [
    "objc2/unstable-darwin-objc",
    "objc2-app-kit/unstable-darwin-objc",
    "objc2-foundation/unstable-darwin-objc",
]

[dependencies]
block2 = "0.6.2"
dispatch2 = "0.3.1"
objc2 = "0.6.2"
objc2-foundation = { version = "0.3.2", default-features = false, features = [
    "std",
    "block2",
    "NSNotification",
    "NSObject",
    "NSOperation",
    "NSString",
    "NSThread",
] }

[target.'cfg(target_os = "macos")'.dependencies]
objc2-app-kit = { version = "0.3.2", default-features = false, features = [
    "std",
    "objc2-core-foundation",
    "NSApplication",
    "NSColor",
    "NSControl",
    "NSFont",
    "NSGraphics",
    "NSResponder",
    "NSRunningApplication",
    "NSText",
    "NSTextField",
    "NSView",
    "NSViewController",
    "NSWindow",
    "NSWindowController",
    "NSMenu",
    "NSMenuItem",
] }

[target.'cfg(any(target_os = "ios", target_os = "tvos", target_os = "visionos"))'.dependencies]
objc2-ui-kit = { version = "0.3.1", default-features = false, features = [
    "std",
    "UIApplication",
    "UIResponder",
    "UIScene",
    "UISceneConfiguration",
    "UISceneDefinitions",
    "UISceneOptions",
    "UISceneSession",
    "UIView",
    "UIViewController",
    "UIWindow",
    "UIWindowScene",
] }
