framework = "Carbon"
crate = "objc2-carbon"
required-crates = ["objc2-core-foundation"]
custom-lib-rs = true
macos = "10.0"

# Use AppKit instead
module.CommonPanels.skipped = true
# Empty
module.ImageCapture.skipped = true
module.Ink.skipped = true
# Use ScriptingBridge instead
module.OpenScripting.skipped = true
# Use SecurityInterface instead
module.SecurityHI.skipped = true
# Use NSSpeechRecognizer (or AVFoundation) instead
module.SpeechRecognition.skipped = true

# TODO: Maybe add this in the future?
module.Help.skipped = true

# Uses kUnknownType from MacTypes.h
const.kKeyboardUnknown.use-value = true

# Wrong type of value.
const.kControlFocusNoPart.use-value = true
const.kHIViewFocusNoPart.use-value = true

# Float literals that don't use `.0`
const.kEventDurationSecond.skipped = true
const.kEventDurationMillisecond.skipped = true
const.kEventDurationMicrosecond.skipped = true
const.kEventDurationNanosecond.skipped = true
const.kEventDurationMinute.skipped = true
const.kEventDurationHour.skipped = true
const.kEventDurationDay.skipped = true
const.kEventDurationNoWait.skipped = true
const.kEventDurationForever.skipped = true

# WindowRef is a pointer, not an integer.
const.kFirstWindowOfClass.skipped = true
const.kLastWindowOfClass.skipped = true
const.kFirstWindowOfGroup.skipped = true
const.kLastWindowOfGroup.skipped = true
const.kFirstWindowGroup.skipped = true
const.kLastWindowGroup.skipped = true
const.kUserFocusAuto.skipped = true
const.kScrapRefNone.skipped = true

# Tries to cast to `float`, which isn't supported
const.kWindowOffsetUnchanged.skipped = true

# Literal overflows i32, needs to be cast / converted to a negative literal.
const.kAEDontDisposeOnResume.use-value = true
const.kTXNClearTheseFontFeatures.use-value = true
const.kTXNDecrementTypeSize.use-value = true
const.kMouseUpOutOfSlop.use-value = true

# Uses sizeof(...), which isn't yet supported by header-translator.
const.kTXNTextEncodingAttributeSize.skipped = true
const.kTXNATSUIStyleSize.skipped = true
const.kTXNQDFontNameAttributeSize.skipped = true
const.kTXNQDFontFamilyIDAttributeSize.skipped = true
const.kTXNFontSizeAttributeSize.skipped = true
const.kTXNQDFontSizeAttributeSize.skipped = true
const.kTXNQDFontStyleAttributeSize.skipped = true
const.kTXNQDFontColorAttributeSize.skipped = true

# Private.
const._KeyboardDispatch.skipped = true

##
## Generics
##

fn.HIObjectCopyDelegates.arguments.1.generics = ["CoreFoundation.CFString.CFString", "CoreFoundation.CFArray.CFArray<Carbon.HIToolbox.HIObject.HIObject>"]
fn.CopySymbolicHotKeys.arguments.0.generics = ["CoreFoundation.CFDictionary.CFDictionary<CoreFoundation.CFString.CFString, CoreFoundation.CFType>"]
fn.TISCreateInputSourceList.arguments.0.generics = ["CoreFoundation.CFString.CFString", "CoreFoundation.CFType"]
fn.TISCreateInputSourceList.return.generics = ["Carbon.HIToolbox.TextInputSources.TISInputSource"]
fn.TISCreateASCIICapableInputSourceList.return.generics = ["Carbon.HIToolbox.TextInputSources.TISInputSource"]

##
## Lifetime
##

# This is a creation method, I'm guessing it's retained.
fn.InstallEventLoopTimer.arguments.5.lifetime = "out-pointer-retained"

# This has "Get" in the name, I'm guessing it's not retained.
fn.InvokeDataBrowserGetContextualMenuUPP.arguments.1.lifetime = "out-pointer-not-retained"
fn.InvokeDataBrowserGetContextualMenuUPP.arguments.3.lifetime = "out-pointer-not-retained"

# This is a creation method, I'm guessing it's retained.
fn.HIObjectRegisterSubclass.arguments.7.lifetime = "out-pointer-retained"

# Docs say: This API was mistakenly named as a "Get" API. It behaves as "Copy"
# API. THE CALLER IS RESPONSIBLE FOR RELEASING THE RETURNED SHAPE.
fn.HIThemeGetButtonShape.arguments.2.lifetime = "out-pointer-retained"
fn.HIThemeGetMenuBackgroundShape.arguments.2.lifetime = "out-pointer-retained"
fn.HIThemeGetTabPaneDrawShape.arguments.3.lifetime = "out-pointer-retained"
fn.HIThemeGetTabPaneContentShape.arguments.3.lifetime = "out-pointer-retained"
fn.HIThemeGetTabDrawShape.arguments.2.lifetime = "out-pointer-retained"
fn.HIThemeGetTabShape.arguments.2.lifetime = "out-pointer-retained"
fn.HIThemeGetTrackThumbShape.arguments.1.lifetime = "out-pointer-retained"
fn.HIThemeGetWindowShape.arguments.3.lifetime = "out-pointer-retained"

##
## Pointer bounds
##

# HIToolbox/AEInteraction.h
fn.AESend.arguments.0.bounds = "single"
fn.AESend.arguments.1.bounds = "single"
fn.AEProcessAppleEvent.arguments.0.bounds = "single"
fn.AEResetTimer.arguments.0.bounds = "single"
fn.AEGetInteractionAllowed.arguments.0.bounds = "single"
fn.AESuspendTheCurrentEvent.arguments.0.bounds = "single"
fn.AEResumeTheCurrentEvent.arguments.0.bounds = "single"
fn.AEResumeTheCurrentEvent.arguments.1.bounds = "single"
fn.AEGetTheCurrentEvent.arguments.0.bounds = "single"
fn.AESetTheCurrentEvent.arguments.0.bounds = "single"
fn.InvokeAEIdleUPP.arguments.0.bounds = "single"
fn.InvokeAEIdleUPP.arguments.1.bounds = "single"
fn.InvokeAEIdleUPP.arguments.2.bounds = "single"
fn.InvokeAEFilterUPP.arguments.0.bounds = "single"
fn.InvokeAEFilterUPP.arguments.3.bounds = "single"

# HIToolbox/Appearance.h
fn.InvokeThemeTabTitleDrawUPP.arguments.0.bounds = "single"
fn.InvokeThemeEraseUPP.arguments.0.bounds = "single"
fn.InvokeThemeButtonDrawUPP.arguments.0.bounds = "single"
fn.InvokeThemeButtonDrawUPP.arguments.2.bounds = "single"
fn.InvokeWindowTitleDrawingUPP.arguments.0.bounds = "single"
fn.InvokeMenuTitleDrawingUPP.arguments.0.bounds = "single"
fn.InvokeMenuItemDrawingUPP.arguments.0.bounds = "single"

# HIToolbox/CarbonEventsCore.h
fn.ReceiveNextEvent.arguments.1.bounds.counted-by = "in_num_types"
fn.ReceiveNextEvent.arguments.4.bounds = "single"
fn.CreateEvent.arguments.5.bounds = "single"
fn.SetEventParameter.arguments.4.bounds.sized-by = "in_size"
fn.GetEventParameter.arguments.3.bounds = "single"
fn.GetEventParameter.arguments.5.bounds = "single"
fn.GetEventParameter.arguments.6.bounds.sized-by = "in_buffer_size"
fn.CreateEventWithCGEvent.arguments.3.bounds = "single"
fn.FlushEventsMatchingListFromQueue.arguments.2.bounds.counted-by = "in_num_types"
fn.AcquireFirstMatchingEventInQueue.arguments.2.bounds.counted-by = "in_num_types"
fn.HIGetMousePosition.arguments.2.bounds = "single"
fn.HIGetMousePosition.return.bounds = "single"
fn.InstallEventHandler.arguments.3.bounds.counted-by = "in_num_types"
fn.InstallEventHandler.arguments.5.bounds = "single"
fn.AddEventTypesToHandler.arguments.2.bounds.counted-by = "in_num_types"
fn.RemoveEventTypesFromHandler.arguments.2.bounds.counted-by = "in_num_types"

# HIToolbox/CarbonEvents.h
fn.HIMouseTrackingGetParameters.arguments.1.bounds = "single"
fn.HIMouseTrackingGetParameters.arguments.2.bounds = "single"
fn.ProcessHICommand.arguments.0.bounds = "single"
fn.RegisterEventHotKey.arguments.5.bounds = "single"
# Unregistering the event hot key deallocates it (probably)
fn.UnregisterEventHotKey.arguments.0.bounds = "unsafe"

# HIToolbox/Controls.h
fn.InvokeControlKeyFilterUPP.arguments.1.bounds = "single"
fn.InvokeControlKeyFilterUPP.arguments.2.bounds = "single"
fn.InvokeControlKeyFilterUPP.arguments.3.bounds = "single"

# HIToolbox/Dialogs.h
fn.InvokeModalFilterUPP.arguments.1.bounds = "single"
fn.InvokeModalFilterUPP.arguments.2.bounds = "single"
fn.InvokeModalFilterYDUPP.arguments.1.bounds = "single"
fn.InvokeModalFilterYDUPP.arguments.2.bounds = "single"

# HIToolbox/Drag.h
fn.InvokeDragInputUPP.arguments.0.bounds = "single"
fn.InvokeDragInputUPP.arguments.1.bounds = "single"

# HIToolbox/Events.h
fn.IsCmdChar.arguments.0.bounds = "single"

# HIToolbox/HIDataBrowser.h
fn.InvokeDataBrowserAddDragItemUPP.arguments.3.bounds = "single"
fn.InvokeDataBrowserGetContextualMenuUPP.arguments.2.bounds = "single"
fn.InvokeDataBrowserGetContextualMenuUPP.arguments.4.bounds = "single"
fn.InvokeDataBrowserItemHelpContentUPP.arguments.4.bounds = "single"
fn.InvokeDataBrowserItemHelpContentUPP.arguments.5.bounds = "single"
fn.InvokeDataBrowserDrawItemUPP.arguments.4.bounds = "single"
fn.InvokeDataBrowserEditItemUPP.arguments.4.bounds = "single"
fn.InvokeDataBrowserEditItemUPP.arguments.5.bounds = "single"
fn.InvokeDataBrowserHitTestUPP.arguments.3.bounds = "single"
fn.InvokeDataBrowserHitTestUPP.arguments.4.bounds = "single"
fn.InvokeDataBrowserTrackingUPP.arguments.3.bounds = "single"
fn.InvokeDataBrowserItemDragRgnUPP.arguments.3.bounds = "single"
fn.InvokeDataBrowserItemAcceptDragUPP.arguments.3.bounds = "single"

# HIToolbox/HIGeometry.h
fn.HIPointConvert.arguments.0.bounds = "single"
fn.HIRectConvert.arguments.0.bounds = "single"
fn.HISizeConvert.arguments.0.bounds = "single"

# HIToolbox/HIObject.h
fn.HIObjectRegisterSubclass.arguments.5.bounds.counted-by = "in_num_events"

# HIToolbox/HITheme.h
fn.HIThemeDrawButton.arguments.0.bounds = "single"
fn.HIThemeDrawButton.arguments.1.bounds = "single"
fn.HIThemeDrawButton.arguments.4.bounds = "single"
fn.HIThemeGetButtonShape.arguments.0.bounds = "single"
fn.HIThemeGetButtonShape.arguments.1.bounds = "single"
fn.HIThemeGetButtonContentBounds.arguments.0.bounds = "single"
fn.HIThemeGetButtonContentBounds.arguments.1.bounds = "single"
fn.HIThemeGetButtonContentBounds.arguments.2.bounds = "single"
fn.HIThemeGetButtonBackgroundBounds.arguments.0.bounds = "single"
fn.HIThemeGetButtonBackgroundBounds.arguments.1.bounds = "single"
fn.HIThemeGetButtonBackgroundBounds.arguments.2.bounds = "single"
fn.HIThemeDrawChasingArrows.arguments.0.bounds = "single"
fn.HIThemeDrawChasingArrows.arguments.1.bounds = "single"
fn.HIThemeDrawPopupArrow.arguments.0.bounds = "single"
fn.HIThemeDrawPopupArrow.arguments.1.bounds = "single"
fn.HIThemeDrawMenuBarBackground.arguments.0.bounds = "single"
fn.HIThemeDrawMenuBarBackground.arguments.1.bounds = "single"
fn.HIThemeDrawMenuTitle.arguments.0.bounds = "single"
fn.HIThemeDrawMenuTitle.arguments.1.bounds = "single"
fn.HIThemeDrawMenuTitle.arguments.2.bounds = "single"
fn.HIThemeDrawMenuTitle.arguments.5.bounds = "single"
fn.HIThemeDrawMenuBackground.arguments.0.bounds = "single"
fn.HIThemeDrawMenuBackground.arguments.1.bounds = "single"
fn.HIThemeDrawMenuItem.arguments.0.bounds = "single"
fn.HIThemeDrawMenuItem.arguments.1.bounds = "single"
fn.HIThemeDrawMenuItem.arguments.2.bounds = "single"
fn.HIThemeDrawMenuItem.arguments.5.bounds = "single"
fn.HIThemeDrawMenuSeparator.arguments.0.bounds = "single"
fn.HIThemeDrawMenuSeparator.arguments.1.bounds = "single"
fn.HIThemeDrawMenuSeparator.arguments.2.bounds = "single"
fn.HIThemeGetMenuBackgroundShape.arguments.0.bounds = "single"
fn.HIThemeGetMenuBackgroundShape.arguments.1.bounds = "single"
fn.HIThemeDrawSegment.arguments.0.bounds = "single"
fn.HIThemeDrawSegment.arguments.1.bounds = "single"
fn.HIThemeDrawTabPane.arguments.0.bounds = "single"
fn.HIThemeDrawTabPane.arguments.1.bounds = "single"
fn.HIThemeDrawTab.arguments.0.bounds = "single"
fn.HIThemeDrawTab.arguments.1.bounds = "single"
fn.HIThemeDrawTab.arguments.4.bounds = "single"
fn.HIThemeGetTabPaneDrawShape.arguments.0.bounds = "single"
fn.HIThemeGetTabPaneContentShape.arguments.0.bounds = "single"
fn.HIThemeGetTabDrawShape.arguments.0.bounds = "single"
fn.HIThemeGetTabDrawShape.arguments.1.bounds = "single"
fn.HIThemeGetTabShape.arguments.0.bounds = "single"
fn.HIThemeGetTabShape.arguments.1.bounds = "single"
fn.HIThemeGetTextDimensions.arguments.2.bounds = "single"
fn.HIThemeGetTextDimensions.arguments.3.bounds = "single"
fn.HIThemeGetTextDimensions.arguments.4.bounds = "single"
fn.HIThemeGetTextDimensions.arguments.5.bounds = "single"
fn.HIThemeDrawTextBox.arguments.1.bounds = "single"
fn.HIThemeDrawTextBox.arguments.2.bounds = "single"
fn.HIThemeDrawTrack.arguments.0.bounds = "single"
fn.HIThemeDrawTrack.arguments.1.bounds = "single"
fn.HIThemeDrawTrackTickMarks.arguments.0.bounds = "single"
fn.HIThemeDrawTickMark.arguments.0.bounds = "single"
fn.HIThemeDrawTickMark.arguments.1.bounds = "single"
fn.HIThemeGetTrackThumbShape.arguments.0.bounds = "single"
fn.HIThemeHitTestTrack.arguments.0.bounds = "single"
fn.HIThemeHitTestTrack.arguments.1.bounds = "single"
fn.HIThemeHitTestTrack.arguments.2.bounds = "single"
fn.HIThemeGetTrackBounds.arguments.0.bounds = "single"
fn.HIThemeGetTrackBounds.arguments.1.bounds = "single"
fn.HIThemeGetTrackPartBounds.arguments.0.bounds = "single"
fn.HIThemeGetTrackPartBounds.arguments.2.bounds = "single"
fn.HIThemeGetTrackParts.arguments.0.bounds = "single"
fn.HIThemeGetTrackParts.arguments.1.bounds = "single"
fn.HIThemeGetTrackParts.arguments.3.bounds.counted-by = "in_max_parts"
fn.HIThemeGetTrackDragRect.arguments.0.bounds = "single"
fn.HIThemeGetTrackDragRect.arguments.1.bounds = "single"
fn.HIThemeGetTrackThumbPositionFromOffset.arguments.0.bounds = "single"
fn.HIThemeGetTrackThumbPositionFromOffset.arguments.1.bounds = "single"
fn.HIThemeGetTrackThumbPositionFromOffset.arguments.2.bounds = "single"
fn.HIThemeGetTrackThumbPositionFromBounds.arguments.0.bounds = "single"
fn.HIThemeGetTrackThumbPositionFromBounds.arguments.1.bounds = "single"
fn.HIThemeGetTrackThumbPositionFromBounds.arguments.2.bounds = "single"
fn.HIThemeGetTrackLiveValue.arguments.0.bounds = "single"
fn.HIThemeGetTrackLiveValue.arguments.2.bounds = "single"
fn.HIThemeGetScrollBarTrackRect.arguments.0.bounds = "single"
fn.HIThemeGetScrollBarTrackRect.arguments.1.bounds = "single"
fn.HIThemeGetScrollBarTrackRect.arguments.3.bounds = "single"
fn.HIThemeHitTestScrollBarArrows.arguments.0.bounds = "single"
fn.HIThemeHitTestScrollBarArrows.arguments.1.bounds = "single"
fn.HIThemeHitTestScrollBarArrows.arguments.3.bounds = "single"
fn.HIThemeHitTestScrollBarArrows.arguments.4.bounds = "single"
fn.HIThemeHitTestScrollBarArrows.arguments.5.bounds = "single"
fn.HIThemeDrawScrollBarDelimiters.arguments.0.bounds = "single"
fn.HIThemeDrawScrollBarDelimiters.arguments.1.bounds = "single"
fn.HIThemeDrawWindowFrame.arguments.0.bounds = "single"
fn.HIThemeDrawWindowFrame.arguments.1.bounds = "single"
fn.HIThemeDrawWindowFrame.arguments.4.bounds = "single"
fn.HIThemeDrawTitleBarWidget.arguments.0.bounds = "single"
fn.HIThemeDrawTitleBarWidget.arguments.1.bounds = "single"
fn.HIThemeDrawGrowBox.arguments.0.bounds = "single"
fn.HIThemeDrawGrowBox.arguments.1.bounds = "single"
fn.HIThemeGetGrowBoxBounds.arguments.0.bounds = "single"
fn.HIThemeGetGrowBoxBounds.arguments.1.bounds = "single"
fn.HIThemeGetGrowBoxBounds.arguments.2.bounds = "single"
fn.HIThemeGetWindowShape.arguments.0.bounds = "single"
fn.HIThemeGetWindowShape.arguments.1.bounds = "single"
fn.HIThemeGetWindowRegionHit.arguments.0.bounds = "single"
fn.HIThemeGetWindowRegionHit.arguments.1.bounds = "single"
fn.HIThemeGetWindowRegionHit.arguments.2.bounds = "single"
fn.HIThemeGetWindowRegionHit.arguments.3.bounds = "single"
fn.HIThemeDrawFrame.arguments.0.bounds = "single"
fn.HIThemeDrawFrame.arguments.1.bounds = "single"
fn.HIThemeDrawGroupBox.arguments.0.bounds = "single"
fn.HIThemeDrawGroupBox.arguments.1.bounds = "single"
fn.HIThemeDrawGenericWell.arguments.0.bounds = "single"
fn.HIThemeDrawGenericWell.arguments.1.bounds = "single"
fn.HIThemeDrawPaneSplitter.arguments.0.bounds = "single"
fn.HIThemeDrawPaneSplitter.arguments.1.bounds = "single"
fn.HIThemeDrawGrabber.arguments.0.bounds = "single"
fn.HIThemeDrawGrabber.arguments.1.bounds = "single"
fn.HIThemeDrawPlacard.arguments.0.bounds = "single"
fn.HIThemeDrawPlacard.arguments.1.bounds = "single"
fn.HIThemeDrawHeader.arguments.0.bounds = "single"
fn.HIThemeDrawHeader.arguments.1.bounds = "single"
fn.HIThemeDrawFocusRect.arguments.0.bounds = "single"
fn.HIThemeDrawSeparator.arguments.0.bounds = "single"
fn.HIThemeDrawSeparator.arguments.1.bounds = "single"
fn.HIThemeApplyBackground.arguments.0.bounds = "single"
fn.HIThemeApplyBackground.arguments.1.bounds = "single"
fn.HIThemeDrawBackground.arguments.0.bounds = "single"
fn.HIThemeDrawBackground.arguments.1.bounds = "single"
fn.HIThemeGetTextColorForThemeBrush.arguments.2.bounds = "single"
fn.GetThemeMenuSeparatorHeight.arguments.0.bounds = "single"
fn.GetThemeMenuItemExtra.arguments.1.bounds = "single"
fn.GetThemeMenuItemExtra.arguments.2.bounds = "single"
fn.GetThemeMenuTitleExtra.arguments.0.bounds = "single"
fn.GetThemeMetric.arguments.1.bounds = "single"

# HIToolbox/IMKInputSession.h
protocol.IMKTextInput.methods."characterIndexForPoint:tracking:inMarkedRange:".arguments.2.bounds = "single"
protocol.IMKTextInput.methods."attributesForCharacterIndex:lineHeightRectangle:".arguments.1.bounds = "single"

# HIToolbox/Lists.h
fn.InvokeListDefUPP.arguments.2.bounds = "single"

# HIToolbox/MacApplication.h
fn.GetSystemUIMode.arguments.0.bounds = "single"
fn.GetSystemUIMode.arguments.1.bounds = "single"
fn.HIDictionaryWindowShow.arguments.6.bounds = "single"

# HIToolbox/MacHelp.h
fn.InvokeHMControlContentUPP.arguments.3.bounds = "single"
fn.InvokeHMControlContentUPP.arguments.4.bounds = "single"
fn.InvokeHMWindowContentUPP.arguments.3.bounds = "single"
fn.InvokeHMWindowContentUPP.arguments.4.bounds = "single"
fn.InvokeHMMenuTitleContentUPP.arguments.2.bounds = "single"
fn.InvokeHMMenuTitleContentUPP.arguments.3.bounds = "single"
fn.InvokeHMMenuItemContentUPP.arguments.0.bounds = "single"
fn.InvokeHMMenuItemContentUPP.arguments.2.bounds = "single"
fn.InvokeHMMenuItemContentUPP.arguments.3.bounds = "single"

# HIToolbox/MacTextEditor.h
fn.InvokeTXNFindUPP.arguments.0.bounds = "single"
fn.InvokeTXNFindUPP.arguments.3.bounds.sized-by = "search_text_length"
fn.InvokeTXNFindUPP.arguments.7.bounds = "single"
fn.InvokeTXNFindUPP.arguments.8.bounds = "single"
fn.InvokeTXNFindUPP.arguments.9.bounds = "single"

# HIToolbox/Menus.h
fn.GetMenuTrackingData.arguments.1.bounds = "single"
fn.CMPluginExamineContext.arguments.1.bounds = "single"
fn.CMPluginExamineContext.arguments.2.bounds = "single"
fn.CMPluginHandleSelection.arguments.1.bounds = "single"

# HIToolbox/TextEdit.h
fn.InvokeHighHookUPP.arguments.0.bounds = "single"
fn.InvokeCaretHookUPP.arguments.0.bounds = "single"
fn.InvokeNWidthHookUPP.arguments.5.bounds = "single"
fn.InvokeHitTestHookUPP.arguments.6.bounds = "single"
fn.InvokeHitTestHookUPP.arguments.7.bounds = "single"
fn.InvokeHitTestHookUPP.arguments.8.bounds = "single"
fn.InvokeTEFindWordUPP.arguments.4.bounds = "single"
fn.InvokeTEFindWordUPP.arguments.5.bounds = "single"
fn.InvokeTERecalcUPP.arguments.2.bounds = "single"
fn.InvokeTERecalcUPP.arguments.3.bounds = "single"
fn.InvokeTERecalcUPP.arguments.4.bounds = "single"
fn.InvokeTEDoTextUPP.arguments.4.bounds = "single"
fn.InvokeTEDoTextUPP.arguments.5.bounds = "single"

# HIToolbox/TextServices.h
fn.TSMGetDocumentProperty.arguments.3.bounds = "single"
fn.TSMGetDocumentProperty.arguments.4.bounds.sized-by = "buffer_size"
