framework = "AVFAudio"
crate = "objc2-avf-audio"
required-crates = ["objc2", "objc2-foundation"]
custom-lib-rs = true
flags = [
    # Make AudioToolbox less dependent on CoreServices
    "-DAUDIOCOMPONENT_NOCARBONINSTANCES=1",
]
# The documentation says something newer here, but since AVFAudio was
# originally available as part of AVFoundation, the linker is able to figure
# out that it actually needs to link AVFoundation because of the $ld$previous$
# directives in AVFAudio.tdb.
macos = "10.7"
maccatalyst = "13.1"
ios = "2.2"
tvos = "9.0"
watchos = "3.0"
visionos = "1.0"

typedef.AVAudioNodeCompletionHandler.sendable = true
typedef.AVAudioPlayerNodeCompletionHandler.sendable = true
typedef.AVMIDIPlayerCompletionHandler.sendable = true

# AUMIDIEventListBlock not currently exported by AudioToolbox
class.AVAudioEngine.methods."connectMIDI:to:format:eventListBlock:".skipped = true
class.AVAudioEngine.methods."connectMIDI:toNodes:format:eventListBlock:".skipped = true

# Both the NSObject superclass and the AVAudioSessionDeprecated category defines this
class.AVAudioSession.methods.init.skipped = true
class.AVAudioSession.methods.new.skipped = true # Use sharedInstance

# Integer return type in error method, unclear how to handle yet
class.AVAudioSequencer.methods."hostTimeForBeats:error:".skipped = true
class.AVAudioSequencer.methods."beatsForHostTime:error:".skipped = true
class.AVAudioEngine.methods."renderOffline:toBuffer:error:".skipped = true

# Needs AppKit or UIKit
class.AVAudioUnitComponent.methods.icon.skipped = true

# Needs CASpatialAudioExperience, which is not available on macOS (where header-translator runs).
class.AVAudioOutputNode.methods.intendedSpatialExperience.skipped = true
class.AVAudioOutputNode.methods."setIntendedSpatialExperience:".skipped = true
class.AVAudioPlayer.methods.intendedSpatialExperience.skipped = true
class.AVAudioPlayer.methods."setIntendedSpatialExperience:".skipped = true

class.AVAudioBuffer.skipped-protocols = ["NSMutableCopying"]
class.AVAudioPCMBuffer.skipped-protocols = ["NSMutableCopying"]
class.AVAudioCompressedBuffer.skipped-protocols = ["NSMutableCopying"]

##
## Pointer bounds
##

class.AVAudioBuffer.methods.audioBufferList.return.bounds = "single"
class.AVAudioBuffer.methods.mutableAudioBufferList.return.bounds = "single"
class.AVAudioPCMBuffer.methods."initWithPCMFormat:bufferListNoCopy:deallocator:".arguments.1.bounds = "single"
class.AVAudioPCMBuffer.methods.floatChannelData.return.bounds.counted-by = "self.format().channelCount()"
class.AVAudioPCMBuffer.methods.int16ChannelData.return.bounds.counted-by = "self.format().channelCount()"
class.AVAudioPCMBuffer.methods.int32ChannelData.return.bounds.counted-by = "self.format().channelCount()"
class.AVAudioCompressedBuffer.methods.packetDescriptions.return.bounds = "unsafe" # Probably self.packetCount(), though unsure
class.AVAudioCompressedBuffer.methods.packetDependencies.return.bounds = "unsafe" # Probably self.packetCount(), though unsure
class.AVAudioChannelLayout.methods."initWithLayout:".arguments.0.bounds = "single"
class.AVAudioChannelLayout.methods."layoutWithLayout:".arguments.0.bounds = "single"
class.AVAudioChannelLayout.methods.layout.return.bounds = "single"
class.AVAudioFormat.methods."initWithStreamDescription:".arguments.0.bounds = "single"
class.AVAudioFormat.methods."initWithStreamDescription:channelLayout:".arguments.0.bounds = "single"
class.AVAudioFormat.methods.streamDescription.return.bounds = "single"
class.AVAudioTime.methods."initWithAudioTimeStamp:sampleRate:".arguments.0.bounds = "single"
class.AVAudioTime.methods."timeWithAudioTimeStamp:sampleRate:".arguments.0.bounds = "single"
class.AVAudioUnitMIDIInstrument.methods."sendMIDIEventList:".arguments.0.bounds = "single"
